# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.repro.core import repro_defined_vars as repro_defined_vars
from metacheck.repro.core import repro_dependencies as repro_dependencies
from metacheck.repro.core import repro_file_io as repro_file_io
from metacheck.repro.core import repro_install_deps as repro_install_deps
from metacheck.repro.core import repro_materialize_layout as repro_materialize_layout
from metacheck.repro.core import repro_missing_inputs as repro_missing_inputs
from metacheck.repro.core import repro_rewrite_paths as repro_rewrite_paths
from metacheck.repro.core import repro_run_order as repro_run_order
from metacheck.repro.core import repro_run_scripts as repro_run_scripts
from metacheck.repro.core import repro_write_scripts as repro_write_scripts
from metacheck.repro.docker import repro_docker_available as repro_docker_available
from metacheck.repro.docker import repro_install_deps_docker as repro_install_deps_docker
from metacheck.repro.docker import repro_run_scripts_docker as repro_run_scripts_docker
from metacheck.repro.tables import capture_module_tables as capture_module_tables
from metacheck.repro.tables import collect_module_tables as collect_module_tables

def __getattr__(name: str) -> Any: ...
