# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.statout.jasp import export_jasp_html as export_jasp_html
from metacheck.statout.jasp import import_jasp as import_jasp
from metacheck.statout.mplus import export_mplus_html as export_mplus_html
from metacheck.statout.mplus import import_mplus_output as import_mplus_output
from metacheck.statout.omv import export_omv_html as export_omv_html
from metacheck.statout.omv import import_omv as import_omv
from metacheck.statout.spv import export_spv_html as export_spv_html
from metacheck.statout.spv import import_spv as import_spv
from metacheck.statout.spv import spv_assemble_table as spv_assemble_table
from metacheck.statout.stata import export_stata_smcl_html as export_stata_smcl_html
from metacheck.statout.stata import import_stata_smcl as import_stata_smcl

def __getattr__(name: str) -> Any: ...
