"""Python sides of the datacheck_files parity cases that inspect side effects.

The R sides are ``$expr`` blocks in ``parity/cases/datacheck_files.yaml``
(generated by ``tests/datacheck_files/gen_parity_cases.py``).
"""

from __future__ import annotations

import datetime as dt
import json
import math
import tempfile
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pandas as pd

from metacheck.datacheck import files as F

ROOT = Path(__file__).resolve().parents[2]
DATA = "tests/datacheck_files/data"


class _NamedList:
    """R's ``as.list(c(a = 1, a = 2))``: a named list that may repeat names."""

    def __init__(self, pairs: list[tuple[Any, Any]]) -> None:
        self.pairs = pairs

    def to_canonical(self, encode: Callable[[Any], dict[str, Any]]) -> dict[str, Any]:
        return {
            "t": "list",
            "names": ["" if k is None else str(k) for k, _ in self.pairs],
            "v": [encode(v) for _, v in self.pairs],
        }


def _r_attributes(df: pd.DataFrame) -> _NamedList:
    """Per-column R attributes (minus levels/names) as R's ``attributes()`` shows them.

    The R side's ``lapply(d, ...)`` is a list named by the columns, a repeated
    column name included. ``labels`` (``(label, code)`` pairs) is compared as
    the R side's ``as.list(labels)``, repeated label texts included.
    """
    from metacheck.datacheck._colattrs import col_attrs_at

    out: list[tuple[Any, Any]] = []
    for j, name in enumerate(df.columns):
        s = df.iloc[:, j]
        attrs = dict(col_attrs_at(df, j))
        attrs.pop("levels", None)
        if isinstance(attrs.get("labels"), list):
            attrs["labels"] = _NamedList(attrs["labels"])
        if "class" not in attrs:
            if isinstance(s.dtype, pd.CategoricalDtype):
                attrs["class"] = ["ordered", "factor"] if s.cat.ordered else "factor"
            elif pd.api.types.is_datetime64_any_dtype(s.dtype):
                attrs["class"] = ["POSIXct", "POSIXt"]
                attrs["tzone"] = str(s.dt.tz) if s.dt.tz is not None else ""
            elif s.dtype == object and any(
                isinstance(v, dt.date) and not isinstance(v, dt.datetime) for v in s.tolist()
            ):
                attrs["class"] = "Date"
        out.append((str(name), {k: attrs[k] for k in sorted(attrs)} if attrs else None))
    return _NamedList(out)


def read_head_attrs(path: str, n_rows: float | None = None) -> dict[str, Any]:
    n = math.inf if n_rows is None else n_rows
    df = F.data_read_head(str(ROOT / path), n_rows=n)
    if df is None:
        return {"names": None, "attrs": None, "utf8_repaired": None}
    return {
        "names": [str(c) for c in df.columns],
        "attrs": _r_attributes(df),
        "utf8_repaired": df.attrs.get("utf8_repaired") or None,
    }


def frame_attr(x: Any, which: str) -> Any:
    """``attr(x, which)`` for a data frame returned by a port."""
    if x is None:
        return None
    return x.attrs.get(which)


def _decode_steps(value: Any) -> Any:
    if isinstance(value, dict):
        if list(value) == ["$rnull"]:
            return F.R_NULL
        return {k: _decode_steps(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_decode_steps(v) for v in value]
    return value


def manifest_merge_lines(steps: list[dict[str, Any]]) -> list[str]:
    """Apply manifest_merge() patches in turn and return the file's lines."""
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "m.json"
        for patch in steps:
            F.manifest_merge(path, _decode_steps(patch))
        return path.read_text(encoding="utf-8").splitlines()


def _manifest_files(**cols: Any) -> pd.DataFrame:
    return pd.DataFrame(cols)


def _stable(doc: Any) -> Any:
    """Blank the run-specific ``generated`` / ``provenance`` fields (both sides)."""
    if isinstance(doc, list):
        return [_stable(d) for d in doc]
    doc = dict(doc)
    doc["generated"] = "<volatile>"
    doc["provenance"] = "<volatile>"
    return doc


def write_manifest_json(scenario: str) -> Any:
    """Run .data_check_write_manifest() for a scenario and read the JSON back."""
    return _stable(_write_manifest_json(scenario))


def _write_manifest_json(scenario: str) -> Any:
    real = str(ROOT / DATA / "rwrite.csv")
    with tempfile.TemporaryDirectory() as tmp:
        if scenario == "split":
            files = _manifest_files(
                repo_url="https://osf.io/xxxxx",
                file_name=[
                    "gotit.csv",
                    "big.rdata",
                    "stim.mp4",
                    "lost.csv",
                    "nourl.csv",
                    "notes.pdf",
                ],
                file_path=[
                    "gotit.csv",
                    "big.rdata",
                    "stim.mp4",
                    "lost.csv",
                    "nourl.csv",
                    "notes.pdf",
                ],
                file_url=["https://osf.io/download/x/"] * 4 + [None, "https://osf.io/download/y/"],
                file_size=[100.0, 5e8, 1e6, 100.0, 100.0, 100.0],
                data_type=["data", "data", "materials", "data", "data", "documentation"],
                data_format="tabular",
                file_location=[real, None, None, None, None, None],
            )
            path = str(Path(tmp) / "m.json")
            F._data_check_write_manifest(
                path, files, [True, True, False, True, True, False], None, "p1", "data", 100, 500,
                skip_types="materials",
                oversize=pd.DataFrame({"repo_url": ["https://osf.io/xxxxx"],
                                       "file_name": ["big.rdata"], "file_size": [5e8]}),
                failed=pd.DataFrame({"repo_url": ["https://osf.io/xxxxx"],
                                     "file_name": ["lost.csv"],
                                     "error": ["HTTP 429 Too Many Requests.\ndetails"]}),
                model="test-model",
            )  # fmt: skip
            return json.loads(Path(path).read_text(encoding="utf-8"))
        if scenario == "none":
            files = _manifest_files(
                repo_url=["https://osf.io/xxxxx"], file_name=["a.csv"], file_path=["a.csv"],
                file_url=["https://osf.io/download/x/"], file_size=[10.0], data_type=["data"],
                data_format=["tabular"], file_location=[None], provider=["osfstorage"],
            )  # fmt: skip
            path = str(Path(tmp) / "m.json")
            F._data_check_write_manifest(
                path, files, True, None, "p1", "none", 100, 500, skip_types="materials"
            )
            return json.loads(Path(path).read_text(encoding="utf-8"))
        if scenario == "per_paper":
            files = _manifest_files(
                paper_id=["paperA", "paperB"],
                repo_url=["https://osf.io/aaaaa", "https://osf.io/bbbbb"],
                file_name=["dataA.csv", "dataB.csv"], file_path=["dataA.csv", "dataB.csv"],
                file_url=["https://osf.io/download/aaaaa/", "https://osf.io/download/bbbbb/"],
                file_size=[100.0, 100.0], data_type=["data", "data"],
                data_format=["tabular", "tabular"], file_location=[real, None],
            )  # fmt: skip
            failed = pd.DataFrame({"repo_url": ["https://osf.io/bbbbb"],
                                   "file_name": ["dataB.csv"],
                                   "error": ["download failed (nothing was written)"]})  # fmt: skip
            paths = F._data_check_write_manifest(
                tmp,
                files,
                [True, True],
                None,
                ["paperA", "paperB"],
                "data",
                100,
                500,
                failed=failed,
            )
            return [json.loads(Path(p).read_text(encoding="utf-8"))
                    for p in sorted(paths, key=lambda p: Path(p).name)]  # fmt: skip
        if scenario == "empty":
            files = pd.DataFrame({"repo_url": pd.Series([], dtype="string"),
                                  "file_name": pd.Series([], dtype="string")})  # fmt: skip
            paths = F._data_check_write_manifest(
                tmp, files, [], None, ["p1", "p2"], "data", None, math.inf
            )
            return [json.loads(Path(p).read_text(encoding="utf-8"))
                    for p in sorted(paths, key=lambda p: Path(p).name)]  # fmt: skip
    raise ValueError(scenario)
