"""Python sides of the datacheck_files_review parity cases.

The R sides are ``$expr`` blocks in ``parity/cases/datacheck_files_review.yaml``
(generated by ``tests/datacheck_files/gen_review_cases.py``). The typed helpers
report each column's R ``typeof()`` and ``class()`` next to the data, because
the canonical comparison alone treats integer and double (and factor and
character) as equal.
"""

from __future__ import annotations

import datetime as dt
import json
import math
import tempfile
from pathlib import Path
from typing import Any

import pandas as pd

from pytacheck.datacheck import files as F

ROOT = Path(__file__).resolve().parents[2]


def r_type(s: pd.Series, attrs: dict[str, Any]) -> list[str]:
    """``c(typeof(x), class(x))`` of a column read by pytacheck."""
    cls = attrs.get("class")
    classes = [cls] if isinstance(cls, str) else list(cls or [])
    d = s.dtype
    if isinstance(d, pd.CategoricalDtype):
        return ["integer", *(classes or (["ordered", "factor"] if d.ordered else ["factor"]))]
    if pd.api.types.is_datetime64_any_dtype(d):
        return ["double", *(classes or ["POSIXct", "POSIXt"])]
    if str(d) == "boolean" or pd.api.types.is_bool_dtype(d):
        return ["logical", *(classes or ["logical"])]
    if pd.api.types.is_integer_dtype(d):
        if "integer64" in classes:
            return ["double", *classes]
        return ["integer", *(classes or ["integer"])]
    if pd.api.types.is_complex_dtype(d):
        return ["complex", *(classes or ["complex"])]
    if pd.api.types.is_float_dtype(d):
        return ["double", *(classes or ["numeric"])]
    if isinstance(d, pd.StringDtype):
        return ["character", *(classes or ["character"])]
    if "Date" in classes:
        return ["integer" if "IDate" in classes else "double", *classes]
    vals = [v for v in s.tolist() if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if vals and all(isinstance(v, dt.date) and not isinstance(v, dt.datetime) for v in vals):
        return ["double", "Date"]
    return ["character", *(classes or ["character"])]


def _typed(df: pd.DataFrame | None) -> dict[str, Any] | None:
    if df is None:
        return None
    from pytacheck.datacheck._files_rdata import _complex_as_character

    col_attrs = df.attrs.get("col_attrs", {})
    types = [r_type(df.iloc[:, j], col_attrs.get(str(c), {})) for j, c in enumerate(df.columns)]
    data = df.copy()
    for j in range(data.shape[1]):
        if pd.api.types.is_complex_dtype(data.iloc[:, j].dtype):
            data.isetitem(
                j, pd.array([_complex_as_character(z) for z in data.iloc[:, j]], dtype="string")
            )
    return {"names": [str(c) for c in df.columns], "types": types, "data": data}


def read_head_typed(path: str, n_rows: float | None = None) -> dict[str, Any] | None:
    """``data_read_head(path, n_rows)`` with each column's R type."""
    n = math.inf if n_rows is None else n_rows
    return _typed(F.data_read_head(str(ROOT / path), n_rows=n))


def read_delim_typed(
    path: str, sep: str, header: bool, nrows: float | None = None, encoding: str | None = None
) -> dict[str, Any] | None:
    """``utils::read.delim(path, sep, header, nrows, check.names = FALSE)`` with R types."""
    from pytacheck.datacheck._files_readers import read_delim

    n = math.inf if nrows is None else nrows
    return _typed(read_delim(str(ROOT / path), sep=sep, header=header, nrows=n, encoding=encoding))


def manifest_scenario(scenario: str) -> Any:
    """Run ``.data_check_write_manifest()`` for a review scenario."""
    with tempfile.TemporaryDirectory() as tmp:
        if scenario == "no_repo_url":
            files = pd.DataFrame(
                {"file_name": ["a.csv", "b.pdf"], "file_url": [None, "https://osf.io/b/"],
                 "data_type": ["data", "documentation"]}
            )  # fmt: skip
            path = str(Path(tmp) / "m.json")
            F._data_check_write_manifest(path, files, [True, False], None, "p1", "data", 100, 500)
            doc = json.loads(Path(path).read_text(encoding="utf-8"))
            return {**doc, "generated": "<volatile>", "provenance": "<volatile>"}
        if scenario == "no_repo_url_gated":  # R: if (NULL %in% gated_urls) is an error
            files = pd.DataFrame({"file_name": ["b.csv"], "file_url": ["https://osf.io/b/"]})
            path = str(Path(tmp) / "m.json")
            F._data_check_write_manifest(path, files, [True], None, "p1", "data", 100, 500)
            return json.loads(Path(path).read_text(encoding="utf-8"))
        if scenario == "dir_slash":
            files = pd.DataFrame({"repo_url": ["u"], "file_name": ["a.csv"]})
            paths = F._data_check_write_manifest(
                tmp + "/out/", files, [False], None, "P 1", "data", 100, 500
            )
            return [p.replace(tmp, "<tmp>") for p in paths]
    raise ValueError(scenario)
