# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.archives.aspredicted import aspredicted_info as aspredicted_info
from metacheck.archives.aspredicted import aspredicted_links as aspredicted_links
from metacheck.archives.cache import metacheck_cache_info as metacheck_cache_info
from metacheck.archives.info_cache import repo_info_cache as repo_info_cache
from metacheck.archives.info_cache import repo_info_cache_clear as repo_info_cache_clear
from metacheck.archives.local import local_files as local_files
from metacheck.archives.osf import osf_api_check as osf_api_check
from metacheck.archives.osf import osf_cache_clear as osf_cache_clear
from metacheck.archives.osf import osf_check_id as osf_check_id
from metacheck.archives.osf import osf_delay as osf_delay
from metacheck.archives.osf import osf_file_download as osf_file_download
from metacheck.archives.osf import osf_get_all_pages as osf_get_all_pages
from metacheck.archives.osf import osf_info as osf_info
from metacheck.archives.osf import osf_links as osf_links
from metacheck.archives.osf import osf_preprint_list as osf_preprint_list
from metacheck.archives.osf import osf_type as osf_type
from metacheck.archives.osf_helpers import osf_pat as osf_pat
from metacheck.archives.osf_helpers import osf_user_projects as osf_user_projects
from metacheck.archives.zip_peek_cache import zip_peek_cache_clear as zip_peek_cache_clear

def __getattr__(name: str) -> Any: ...
