# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.datacheck.files import data_classify_files as data_classify_files
from metacheck.datacheck.files import data_format as data_format
from metacheck.datacheck.files import data_group_llm as data_group_llm
from metacheck.datacheck.files import data_is_manifest as data_is_manifest
from metacheck.datacheck.files import data_read_head as data_read_head
from metacheck.datacheck.files import data_study_roster as data_study_roster
from metacheck.datacheck.files import manifest_merge as manifest_merge
from metacheck.datacheck.files import rscript_path as rscript_path
from metacheck.datacheck.files import text_peek as text_peek
from metacheck.datacheck.files import txt_classify_content as txt_classify_content

def __getattr__(name: str) -> Any: ...
