"""Data-quality checks, PII detection, column concepts and source-format detection.

Port of ``R/data_check_helpers.R`` from ``data_check_scale_values()`` to the
end of the file: the per-column checks ``data_check`` runs, split by theme
into private submodules and re-exported here.

* single-column quality -- :func:`data_check_scale_values`,
  :func:`data_check_outliers`, :func:`data_check_constant`,
  :func:`data_check_empty`, :func:`data_check_design_name`,
  :func:`data_check_spss_filter`, :func:`data_check_case_issues`,
  :func:`data_check_whitespace`, :func:`data_check_numeric_in_text`,
  :func:`data_check_colname`, :func:`data_check_colname_collisions`;
* personal information -- :func:`data_check_pii_values`,
  :func:`data_check_pii_name`, :func:`data_check_pii_geo`,
  :func:`data_check_pii_freetext`, :func:`data_check_demographic`;
* column facets -- :func:`data_col_concept`, :func:`data_col_facets`;
* file formats -- :func:`data_check_is_qualtrics`,
  :func:`data_strip_qualtrics_header`, :func:`data_promote_header_row`,
  :func:`data_check_is_behaverse`, :func:`data_check_is_inquisit`,
  :func:`data_check_is_jspsych`, :func:`data_check_is_psychopy`;
* scale / task blocks -- ``_detect_scale_blocks()``,
  ``_detect_task_columns()``, ``_detect_accuracy_blocks()`` and friends.

Every function accepts R-like vectors: lists, tuples, ``numpy`` arrays and
``pandas`` Series (their dtype gives the R type: ``Int64``/``float64`` are
numeric, ``boolean`` logical, ``string``/``object`` character, ``category``
a factor). Missing values are ``None``/NaN/``pd.NA``. Results are dicts
mirroring R's lists; R's ``NA`` scalars are ``None`` (NaN for the numeric
``lower``/``upper`` bounds) and ``NULL`` is ``None``.
"""

from __future__ import annotations

from pytacheck.datacheck._checks_blocks import (
    _SCALE_MIN_ITEMS,
    _TASK_ACC_MIN_ITEMS,
    _detect_accuracy_blocks,
    _detect_scale_blocks,
    _detect_task_columns,
    _is_accuracy_item,
    _is_likert_item,
    _is_task_data,
    _looks_like_accuracy,
    _looks_like_rt,
    _scale_block_is_ratinglike,
    _scale_block_range,
    _scale_name_prefix,
)
from pytacheck.datacheck._checks_facets import (
    _ACC_NAME_RE,
    _DATE_FMTS,
    _DATETIME_FMTS,
    _RT_NAME_RE,
    _TABULAR_MISS_MID,
    _TABULAR_PROSE_HIGH,
    _TABULAR_PROSE_MID,
    _coltype_to_facets,
    _concept_is_accuracy,
    _concept_is_condition,
    _concept_is_date,
    _concept_is_rt,
    _concept_is_timestamp,
    _parse_frac,
    _tabular_usable,
    data_col_concept,
    data_col_facets,
)
from pytacheck.datacheck._checks_format import (
    _QUALTRICS_META_COLS,
    _as_num_safe,
    _bh_is_trial_level_file,
    _detect_header_row,
    _eprime_is_export,
    _is_junk_above_header,
    _is_placeholder_name,
    _numeric_col_fraction,
    _qualtrics_col_stem,
    _qualtrics_is_display_order,
    _qualtrics_is_header_row,
    _qualtrics_key,
    _qualtrics_tag_cols,
    _row_duplication,
    data_check_is_behaverse,
    data_check_is_inquisit,
    data_check_is_jspsych,
    data_check_is_psychopy,
    data_check_is_qualtrics,
    data_promote_header_row,
    data_strip_qualtrics_header,
)
from pytacheck.datacheck._checks_pii import (
    _DEMOGRAPHIC_NAME_REGEX,
    _DEMOGRAPHIC_NAME_TOKENS,
    _PII_NAME_TOKENS,
    _PII_VALUE_PATTERNS,
    _demographic_values_ok,
    _pii_card_ok,
    _pii_luhn_ok,
    _pii_split_name,
    data_check_demographic,
    data_check_pii_freetext,
    data_check_pii_geo,
    data_check_pii_name,
    data_check_pii_values,
)
from pytacheck.datacheck._checks_quality import (
    _DATA_MISSING_SENTINELS,
    data_check_case_issues,
    data_check_colname,
    data_check_colname_collisions,
    data_check_constant,
    data_check_design_name,
    data_check_empty,
    data_check_numeric_in_text,
    data_check_outliers,
    data_check_scale_values,
    data_check_spss_filter,
    data_check_whitespace,
)

__all__ = [
    "data_check_case_issues",
    "data_check_colname",
    "data_check_colname_collisions",
    "data_check_constant",
    "data_check_demographic",
    "data_check_design_name",
    "data_check_empty",
    "data_check_is_behaverse",
    "data_check_is_inquisit",
    "data_check_is_jspsych",
    "data_check_is_psychopy",
    "data_check_is_qualtrics",
    "data_check_numeric_in_text",
    "data_check_outliers",
    "data_check_pii_freetext",
    "data_check_pii_geo",
    "data_check_pii_name",
    "data_check_pii_values",
    "data_check_scale_values",
    "data_check_spss_filter",
    "data_check_whitespace",
    "data_col_concept",
    "data_col_facets",
    "data_promote_header_row",
    "data_strip_qualtrics_header",
]

# private helpers re-exported for the canonical symbol locations (porting/symbols.json)
_PRIVATE = (
    _ACC_NAME_RE,
    _DATA_MISSING_SENTINELS,
    _DATE_FMTS,
    _DATETIME_FMTS,
    _DEMOGRAPHIC_NAME_REGEX,
    _DEMOGRAPHIC_NAME_TOKENS,
    _PII_NAME_TOKENS,
    _PII_VALUE_PATTERNS,
    _QUALTRICS_META_COLS,
    _RT_NAME_RE,
    _SCALE_MIN_ITEMS,
    _TABULAR_MISS_MID,
    _TABULAR_PROSE_HIGH,
    _TABULAR_PROSE_MID,
    _TASK_ACC_MIN_ITEMS,
    _as_num_safe,
    _bh_is_trial_level_file,
    _coltype_to_facets,
    _concept_is_accuracy,
    _concept_is_condition,
    _concept_is_date,
    _concept_is_rt,
    _concept_is_timestamp,
    _demographic_values_ok,
    _detect_accuracy_blocks,
    _detect_header_row,
    _detect_scale_blocks,
    _detect_task_columns,
    _eprime_is_export,
    _is_accuracy_item,
    _is_junk_above_header,
    _is_likert_item,
    _is_placeholder_name,
    _is_task_data,
    _looks_like_accuracy,
    _looks_like_rt,
    _numeric_col_fraction,
    _parse_frac,
    _pii_card_ok,
    _pii_luhn_ok,
    _pii_split_name,
    _qualtrics_col_stem,
    _qualtrics_is_display_order,
    _qualtrics_is_header_row,
    _qualtrics_key,
    _qualtrics_tag_cols,
    _row_duplication,
    _scale_block_is_ratinglike,
    _scale_block_range,
    _scale_name_prefix,
    _tabular_usable,
)
