"""Adversarial checks of bibr 12.x reading and writing (review of metacheck PR #423).

The R results these tests pin down are also parity cases in
``parity/cases/bibr12_review.yaml`` (generated by ``gen_review_cases.py``).
"""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import Any

import orjson
import pandas as pd
import pytest

import pytacheck as pc
from pytacheck.io import bibr12
from pytacheck.papers.io import _dollar

FX = Path(__file__).resolve().parent / "fixtures"


def write_json(tmp_path: Path, data: Any, name: str = "x.json") -> Path:
    path = tmp_path / name
    path.write_bytes(orjson.dumps(data))
    return path


def written(paper: Any, tmp_path: Path) -> dict[str, Any]:
    path = pc.paper_write(paper, None, tmp_path, schema_version="12.0")
    return orjson.loads(Path(path).read_bytes())  # type: ignore[arg-type]


# -- degrees of freedom: if (is.null(df) || grepl("^\\(.*\\)$", df)) ... --------------


@pytest.mark.parametrize(
    ("df", "expected"),
    [
        ("28", "(28)"),
        ("(28)", "(28)"),
        (28, "(28)"),
        (2.5, "(2.5)"),
        (True, "(TRUE)"),
        ("", "()"),
        ("(1) and (2)", "(1) and (2)"),
        ("1,\n2", "(1,\n2)"),
        (["4"], "(4)"),
        (["(5)"], "(5)"),
        ({"k": 6}, "(6)"),
        ([None], "(NULL)"),
    ],
)
def test_eq_df_is_kept_in_parentheses(tmp_path: Path, df: Any, expected: str) -> None:
    path = write_json(
        tmp_path, {"paper_id": "p", "schema_version": "12.0", "eq": [{"eq_id": 1, "df": df}]}
    )
    assert pc.read(path).eq["df"].iloc[0] == expected


@pytest.mark.parametrize(
    ("df", "message"),
    [
        (["(3)", "4"], "'length = 2' in coercion to 'logical(1)'"),
        ([], "missing value where TRUE/FALSE needed"),
    ],
)
def test_eq_df_array_of_other_length_stops_as_in_r(tmp_path: Path, df: Any, message: str) -> None:
    path = write_json(
        tmp_path, {"paper_id": "p", "schema_version": "12.0", "eq": [{"eq_id": 1, "df": df}]}
    )
    with pytest.raises(ValueError, match=message.replace("(", r"\(").replace(")", r"\)")):
        bibr12.read_bibr12(path)


# -- the given/family names of match persons (names_df()) ------------------------------


def test_match_person_names_follow_r() -> None:
    names = bibr12._names_records([{"given": "A", "family": "B"}, None, ["x"], {"given": 5}])
    assert names == [
        {"given": "A", "family": "B"},
        {"given": None, "family": None},  # NULL$given is NULL
        {"given": None, "family": None},  # an unnamed list's $given is NULL
        {"given": "5", "family": None},
    ]
    # a JSON object of persons: vapply() runs over its values
    assert bibr12._names_records({"a": {"family": "F"}}) == [{"given": None, "family": "F"}]
    assert bibr12._names_records({"given": ["A"]}) == [{"given": None, "family": None}]
    assert len(bibr12._names_records([])) == 0
    assert len(bibr12._names_records(None)) == 0


@pytest.mark.parametrize(
    ("persons", "message"),
    [
        (["Smith"], r"\$ operator is invalid for atomic vectors"),
        ("Smith", r"\$ operator is invalid for atomic vectors"),
        (
            [{"given": ["A", "B"]}],
            r"values must be length 1,\n but FUN\(X\[\[1\]\]\) result is length 2",
        ),
        ([{"family": "X"}, {"given": []}], r"FUN\(X\[\[2\]\]\) result is length 0"),
    ],
)
def test_match_person_names_errors_follow_r(persons: Any, message: str) -> None:
    with pytest.raises(ValueError, match=message):
        bibr12._names_records(persons)


def test_null_person_in_match_author_reads(tmp_path: Path) -> None:
    data = {
        "paper_id": "p",
        "schema_version": "12.0",
        "bib_match": [{"bib_id": 1, "service": "crossref", "author": [{"family": "C"}, None]}],
    }
    p = pc.read(write_json(tmp_path, data))
    assert p.bib_match["authors"].iloc[0] == [
        {"given": None, "family": "C"},
        {"given": None, "family": None},
    ]
    # the parsed persons are written back as they were
    assert written(p, tmp_path)["bib_match"][0]["author"] == [{"family": "C"}, None]


# -- the 12.0 writer: arrays --------------------------------------------------------


def test_na_in_an_atomic_array_column_is_written_as_null(tmp_path: Path) -> None:
    """``as.character(unlist(NA))`` is NA: ``[null]``; a NULL cell is ``[]``."""
    p = pc.read(FX / "edge_types.json")
    author = p.author.copy()
    author["role"] = pd.Series(["single", None, "x", "y"], dtype="string")
    author["credit_roles"] = pd.Series([["a"], None, float("nan"), []], dtype=object)
    p.author = author
    rows = written(p, tmp_path)["author"]
    assert [r["role"] for r in rows] == [["single"], [None], ["x"], ["y"]]
    # a list column: None is NULL ([]), NaN is NA ([null])
    assert [r["credit_roles"] for r in rows] == [["a"], [], [None], []]


def test_na_table_contents_is_written_as_nested_null(tmp_path: Path) -> None:
    p = pc.read(FX / "edge_types.json")
    table = p.table.copy()
    table["contents"] = pd.Series(["x", None, "y"], dtype="string")
    p.table = table
    rows = written(p, tmp_path)["table"]
    assert [r["contents"] for r in rows] == [[["x"]], [[None]], [["y"]]]


def test_paper_write_drops_one_file_suffix(tmp_path: Path) -> None:
    p = pc.read(FX / "edge_minimal.json")
    names = ["a.zip.json", "b.json.zip", "c.JSON"]
    paths = [pc.paper_write(p, n, tmp_path, schema_version="12.0") for n in names]
    assert [Path(x).name for x in paths] == ["a.zip.json", "b.json.json", "c.JSON.json"]  # type: ignore[arg-type]


def test_paper_write_recycles_file_names_over_a_paper_list(tmp_path: Path) -> None:
    papers = pc.PaperList([pc.read(FX / "edge_minimal.json"), pc.read(FX / "edge_numeric_id.json")])
    paths = pc.paper_write(papers, "same", tmp_path, schema_version="12.0")
    assert [Path(x).name for x in paths] == ["same.json", "same.json"]  # type: ignore[union-attr]
    # the default: auto per paper (both are 12.x papers)
    paths = pc.paper_write(papers, None, tmp_path)
    assert [orjson.loads(Path(x).read_bytes())["schema_version"] for x in paths] == ["12.0", "12.0"]  # type: ignore[union-attr]


def test_paper_write_auto_mixes_formats_in_a_paper_list(tmp_path: Path) -> None:
    papers = pc.PaperList([pc.demopaper(), pc.read(FX / "edge_minimal.json")])
    paths = pc.paper_write(papers, None, tmp_path)
    data = [orjson.loads(Path(x).read_bytes()) for x in paths]  # type: ignore[union-attr]
    assert "schema_version" not in data[0]  # the older paper object
    assert data[1]["schema_version"] == "12.0"


# -- paper_validate(): R's typeof() in its messages -----------------------------------


def validate_warnings(paper: Any) -> list[str]:
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        assert pc.paper_validate(paper)
    return [str(w.message) for w in caught]


def test_paper_validate_names_r_types() -> None:
    p = pc.read(FX / "edge_minimal.json")
    assert validate_warnings(p) == []
    text = pd.DataFrame(
        {
            "text": pd.Series(["a"], dtype="string"),
            "text_id": pd.Series([1.0]),
            "paragraph_id": pd.Series([1], dtype="Int64"),
            "section_id": pd.Series(["1"], dtype=object),
        }
    )
    p.text = text
    bib_match = p.bib_match.copy()
    bib_match["score"] = pd.Series([], dtype="Int64")
    p.bib_match = bib_match
    (msg,) = validate_warnings(p)
    assert msg == (
        "The text_id column of the text table is a double type, but should be a integer type\n"
        "The section_id column of the text table is a character type, but should be a integer type\n"
        "The score column of the bib_match table is a integer type, but should be a double type"
    )


# -- the older reader: jsonlite's shapes and R's `$` ----------------------------------


def test_older_info_array_keywords_are_the_column() -> None:
    p = pc.read(FX / "legacy_arrays.json")
    assert p.info["keywords"].iloc[0] == [["a", "b"]]
    # an empty cell of a column of record arrays is a 0 x 0 data frame
    authors = p.bib_match["authors"].tolist()
    assert isinstance(authors[0], pd.DataFrame) and authors[0].shape == (0, 0)
    assert authors[1] == [{"given": "A", "family": "B"}]
    # ... unless a cell is null
    p = pc.read(FX / "legacy_arrays_null.json")
    assert p.bib_match["authors"].tolist()[0] == []


def test_older_file_without_bib_reads_bib_match_as_bib() -> None:
    """``data$bib`` partially matches ``bib_match`` (R's ``$``)."""
    p = pc.read(FX / "legacy_no_bib.json")
    assert p.bib["title"].tolist() == ["A", "B"]


def test_dollar_matches_a_unique_prefix() -> None:
    assert _dollar({"bib_match": 1}, "bib") == 1
    assert _dollar({"bib": 0, "bib_match": 1}, "bib") == 0
    assert _dollar({"bib_a": 1, "bib_b": 2}, "bib") is None
    assert _dollar(["x"], "bib") is None


def test_root_schema_version_prefix_goes_to_the_12x_reader(tmp_path: Path) -> None:
    path = write_json(tmp_path, {"paper_id": "p", "schema_version_x": "11.0"})
    with pytest.raises(ValueError, match=r"bibr export schema 11\.0 is not supported"):
        pc.papers.io.read_bibr(path)
