"""Adversarial checks of bibr 12.x reading and writing (review of metacheck PR #423).

The R results these tests pin down are also parity cases in
``parity/cases/bibr12_review.yaml`` (generated by ``gen_review_cases.py``).
"""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import Any

import orjson
import pandas as pd
import pytest

import pytacheck as pc
from pytacheck.io import bibr12
from pytacheck.papers.io import _field

FX = Path(__file__).resolve().parent / "fixtures"


def write_json(tmp_path: Path, data: Any, name: str = "x.json") -> Path:
    path = tmp_path / name
    path.write_bytes(orjson.dumps(data))
    return path


def written(paper: Any, tmp_path: Path) -> dict[str, Any]:
    path = pc.paper_write(paper, None, tmp_path, schema_version="12.0")
    return orjson.loads(Path(path).read_bytes())  # type: ignore[arg-type]


# -- degrees of freedom: if (is.null(df) || grepl("^\\(.*\\)$", df)) ... --------------


@pytest.mark.parametrize(
    ("df", "expected"),
    [
        ("28", "(28)"),
        ("(28)", "(28)"),
        (28, "(28)"),
        (2.5, "(2.5)"),
        (True, "(TRUE)"),
        # no df (metacheck: "()" and "(NULL)"; U24)
        ("", None),
        ("  ", None),
        ([None], None),
        ("(1) and (2)", "(1) and (2)"),
        ("1,\n2", "(1,\n2)"),
        (["4"], "(4)"),
        (["(5)"], "(5)"),
        ({"k": 6}, "(6)"),
        # an array keeps its first value (metacheck stops: "'length = 2' in
        # coercion to 'logical(1)'", "missing value where TRUE/FALSE needed"; U24)
        (["(3)", "4"], "(3)"),
        ([], None),
    ],
)
def test_eq_df_is_kept_in_parentheses(tmp_path: Path, df: Any, expected: str | None) -> None:
    path = write_json(
        tmp_path, {"paper_id": "p", "schema_version": "12.0", "eq": [{"eq_id": 1, "df": df}]}
    )
    got = pc.read(path).eq["df"].iloc[0]
    assert (None if pd.isna(got) else got) == expected


# -- scalar fields holding arrays: row by row (U24) ------------------------------------


def test_scalar_field_arrays_are_read_row_by_row() -> None:
    # metacheck unlist()s the column: bib 1 gets bib 2's title ("B"), bib 2 "C"
    p = pc.read(FX / "malformed" / "scalar_shifted.json")
    assert p.bib["title"].tolist()[0] is pd.NA or pd.isna(p.bib["title"].iloc[0])
    assert p.bib["title"].tolist()[1] == "B"
    # metacheck recycles bib 1's id into bib 2
    p = pc.read(FX / "malformed" / "scalar_null_array_recycled.json")
    assert p.bib["bib_id"].isna().tolist() == [False, True]
    assert p.bib["title"].tolist() == ["A", "B"]
    # metacheck: "replacement has 2 rows, data has 3"
    p = pc.read(FX / "malformed" / "scalar_null_array.json")
    assert len(p.table) == 3


def test_metadata_source_and_producer_arrays_keep_the_first_value() -> None:
    # metacheck: "replacement has 0 rows, data has 1" / "... 2 rows, data has 1"
    assert pd.isna(pc.read(FX / "malformed" / "metadata_null_array.json").info["title"].iloc[0])
    info = pc.read(FX / "malformed" / "source_value_array.json").info
    assert info["file_name"].tolist() == ["a"]
    info = pc.read(FX / "malformed" / "producer_version_array.json").info
    assert info["bibr_version"].tolist() == ["1"]


# -- the given/family names of match persons (names_df()) ------------------------------


def test_match_person_names() -> None:
    names = bibr12._names_records([{"given": "A", "family": "B"}, None, ["x"], {"given": 5}])
    assert names == [
        {"given": "A", "family": "B"},
        {"given": None, "family": None},  # NULL$given is NULL
        {"given": None, "family": None},  # an unnamed list's $given is NULL
        {"given": "5", "family": None},
    ]
    # a JSON object of persons: vapply() runs over its values
    assert bibr12._names_records({"a": {"family": "F"}}) == [{"given": None, "family": "F"}]
    assert bibr12._names_records({"given": ["A"]}) == [{"given": None, "family": None}]
    assert len(bibr12._names_records([])) == 0
    assert len(bibr12._names_records(None)) == 0
    # a name given as an array: its first value (metacheck: "values must be length 1"; U24)
    assert bibr12._names_records([{"given": ["A", "B"]}, {"given": []}, {"given": [None]}]) == [
        {"given": "A", "family": None},
        {"given": None, "family": None},
        {"given": None, "family": None},
    ]


@pytest.mark.parametrize("persons", [["Smith"], "Smith"])
def test_match_person_that_is_not_an_object_stops(persons: Any) -> None:
    with pytest.raises(ValueError, match=r"\$ operator is invalid for atomic vectors"):
        bibr12._names_records(persons)


def test_null_person_in_match_author_reads(tmp_path: Path) -> None:
    data = {
        "paper_id": "p",
        "schema_version": "12.0",
        "bib_match": [{"bib_id": 1, "service": "crossref", "author": [{"family": "C"}, None]}],
    }
    p = pc.read(write_json(tmp_path, data))
    assert p.bib_match["authors"].iloc[0] == [
        {"given": None, "family": "C"},
        {"given": None, "family": None},
    ]
    # the parsed persons are written back as they were
    assert written(p, tmp_path)["bib_match"][0]["author"] == [{"family": "C"}, None]


# -- the 12.0 writer: arrays --------------------------------------------------------


def test_na_in_an_atomic_array_column_is_written_as_null(tmp_path: Path) -> None:
    """``as.character(unlist(NA))`` is NA: ``[null]``; a NULL cell is ``[]``."""
    p = pc.read(FX / "edge_types.json")
    author = p.author.copy()
    author["role"] = pd.Series(["single", None, "x", "y"], dtype="string")
    author["credit_roles"] = pd.Series([["a"], None, float("nan"), []], dtype=object)
    p.author = author
    rows = written(p, tmp_path)["author"]
    assert [r["role"] for r in rows] == [["single"], [None], ["x"], ["y"]]
    # a list column: None is NULL ([]), NaN is NA ([null])
    assert [r["credit_roles"] for r in rows] == [["a"], [], [None], []]


def test_na_table_contents_is_written_as_nested_null(tmp_path: Path) -> None:
    p = pc.read(FX / "edge_types.json")
    table = p.table.copy()
    table["contents"] = pd.Series(["x", None, "y"], dtype="string")
    p.table = table
    rows = written(p, tmp_path)["table"]
    assert [r["contents"] for r in rows] == [[["x"]], [[None]], [["y"]]]


def test_paper_write_drops_one_file_suffix(tmp_path: Path) -> None:
    p = pc.read(FX / "edge_minimal.json")
    names = ["a.zip.json", "b.json.zip", "c.JSON"]
    paths = [pc.paper_write(p, n, tmp_path, schema_version="12.0") for n in names]
    assert [Path(x).name for x in paths] == ["a.zip.json", "b.json.json", "c.JSON.json"]  # type: ignore[arg-type]


def test_paper_write_recycles_file_names_over_a_paper_list(tmp_path: Path) -> None:
    papers = pc.PaperList([pc.read(FX / "edge_minimal.json"), pc.read(FX / "edge_numeric_id.json")])
    paths = pc.paper_write(papers, "same", tmp_path, schema_version="12.0")
    assert [Path(x).name for x in paths] == ["same.json", "same.json"]  # type: ignore[union-attr]
    # the default: auto per paper (both are 12.x papers)
    paths = pc.paper_write(papers, None, tmp_path)
    assert [orjson.loads(Path(x).read_bytes())["schema_version"] for x in paths] == ["12.0", "12.0"]  # type: ignore[union-attr]


def test_paper_write_auto_mixes_formats_in_a_paper_list(tmp_path: Path) -> None:
    papers = pc.PaperList([pc.demopaper(), pc.read(FX / "edge_minimal.json")])
    paths = pc.paper_write(papers, None, tmp_path)
    data = [orjson.loads(Path(x).read_bytes()) for x in paths]  # type: ignore[union-attr]
    assert "schema_version" not in data[0]  # the older paper object
    assert data[1]["schema_version"] == "12.0"


# -- paper_validate(): R's typeof() in its messages -----------------------------------


def validate_warnings(paper: Any) -> list[str]:
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        assert pc.paper_validate(paper)
    return [str(w.message) for w in caught]


def test_paper_validate_names_r_types() -> None:
    p = pc.read(FX / "edge_minimal.json")
    assert validate_warnings(p) == []
    text = pd.DataFrame(
        {
            "text": pd.Series(["a"], dtype="string"),
            "text_id": pd.Series([1.0]),
            "paragraph_id": pd.Series([1], dtype="Int64"),
            "section_id": pd.Series(["1"], dtype=object),
        }
    )
    p.text = text
    bib_match = p.bib_match.copy()
    bib_match["score"] = pd.Series([], dtype="Int64")
    p.bib_match = bib_match
    (msg,) = validate_warnings(p)
    assert msg == (
        "The text_id column of the text table is a double type, but should be a integer type\n"
        "The section_id column of the text table is a character type, but should be a integer type\n"
        "The score column of the bib_match table is a integer type, but should be a double type"
    )


# -- the older reader: jsonlite's shapes and R's `$` ----------------------------------


def test_older_info_array_keywords_are_the_column() -> None:
    p = pc.read(FX / "legacy_arrays.json")
    assert p.info["keywords"].iloc[0] == [["a", "b"]]
    # an empty cell of a column of record arrays is a 0 x 0 data frame
    authors = p.bib_match["authors"].tolist()
    assert isinstance(authors[0], pd.DataFrame) and authors[0].shape == (0, 0)
    assert authors[1] == [{"given": "A", "family": "B"}]
    # ... unless a cell is null
    p = pc.read(FX / "legacy_arrays_null.json")
    assert p.bib_match["authors"].tolist()[0] == []


def test_older_file_without_bib_has_no_references() -> None:
    """Keys match exactly (metacheck's ``data$bib`` partially matches ``bib_match``; U25)."""
    p = pc.read(FX / "legacy_no_bib.json")
    assert len(p.bib) == 0
    assert p.bib_match["title"].tolist() == ["A", "B"]


def test_field_matches_keys_exactly() -> None:
    assert _field({"bib_match": 1}, "bib") is None
    assert _field({"bib": 0, "bib_match": 1}, "bib") == 0
    assert _field(["x"], "bib") is None


def test_root_schema_version_key_must_match_exactly(tmp_path: Path) -> None:
    # metacheck's `$` sends "schema_version_x" to the 12.x reader, which refuses 11.0 (U25)
    path = write_json(tmp_path, {"paper_id": "p", "schema_version_x": "11.0"})
    p = pc.papers.io.read_bibr(path)
    assert p.paper_id == "p"
    assert not bibr12.is_bibr12(p)
    assert p.extra["schema_version_x"] == "11.0"
