"""pytacheck: check research outputs for best practices.

A Python-native, parity-tested port of ScienceVerse's `metacheck
<https://github.com/scienceverse/metacheck>`_ R package, built to work
hand in hand with `bibr <https://bibr.org>`_.

.. code-block:: python

    import pytacheck as pc

    paper = pc.read("paper.json")            # bibr JSON, Grobid XML, or a PDF via bibr
    out = pc.module_run(paper, "all_p_values")
    out.table

Public names are imported lazily so ``import pytacheck`` stays fast.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

from pytacheck._version import UPSTREAM, __version__

# name -> module that defines it. Keep sorted by module.
_EXPORTS: dict[str, str] = {
    # configuration & logging
    "cache_dir": "pytacheck.config",
    "email": "pytacheck.config",
    "verbose": "pytacheck.config",
    "lastlog": "pytacheck.log",
    "logger": "pytacheck.log",
    "logpath": "pytacheck.log",
    # reading
    "read": "pytacheck.io.read",
    "chew": "pytacheck.io.bibr",
    # module system
    "ModuleError": "pytacheck.module",
    "ModuleOutput": "pytacheck.module",
    "ModuleSpec": "pytacheck.module",
    "get_prev_outputs": "pytacheck.module",
    "module": "pytacheck.module",
    "module_help": "pytacheck.module",
    "module_info": "pytacheck.module",
    "module_list": "pytacheck.module",
    "module_run": "pytacheck.module",
    "run_session": "pytacheck.module",
    "use": "pytacheck.module",
    # packs & presets (module system v2; pytacheck.packs is only imported on use)
    "CheckIssue": "pytacheck.packs.check",
    "pack_check": "pytacheck.packs.check",
    "pack_install": "pytacheck.packs.install",
    "pack_list": "pytacheck.packs.install",
    "pack_remove": "pytacheck.packs.install",
    "pack_show": "pytacheck.packs.install",
    "pack_update": "pytacheck.packs.install",
    "refresh": "pytacheck.packs.registry",
    "module_template": "pytacheck.packs.scaffold",
    "pack_new": "pytacheck.packs.scaffold",
    "store_add": "pytacheck.packs.stores",
    "store_list": "pytacheck.packs.stores",
    "store_remove": "pytacheck.packs.stores",
    "store_search": "pytacheck.packs.stores",
    "store_update": "pytacheck.packs.stores",
    "preset": "pytacheck.presets",
    "preset_list": "pytacheck.presets",
    # run records and reproducibility
    "ModuleChain": "pytacheck.provenance",
    "RunRecord": "pytacheck.provenance",
    "rerun": "pytacheck.provenance",
    "run_modules": "pytacheck.provenance",
    # papers
    "Paper": "pytacheck.papers",
    "PaperList": "pytacheck.papers",
    "PaperValidationError": "pytacheck.papers",
    "demofile": "pytacheck.papers",
    "demopaper": "pytacheck.papers",
    "from_bibr": "pytacheck.papers",
    "paper": "pytacheck.papers",
    "paper_id": "pytacheck.papers",
    "paper_table": "pytacheck.papers",
    "paper_validate": "pytacheck.papers",
    "paper_write": "pytacheck.papers",
    "read_bibr": "pytacheck.papers",
    "ref_table": "pytacheck.papers",
    "test_paper": "pytacheck.papers",
    # reports and validation
    "emojis": "pytacheck.report.emojis",
    "module_report": "pytacheck.report.report",
    "report": "pytacheck.report.report",
    "report_module_run": "pytacheck.report.report",
    "report_qmd": "pytacheck.report.report",
    "report_repository": "pytacheck.report.report",
    "report_table": "pytacheck.report.blocks",
    "accuracy": "pytacheck.validate",
    "validate": "pytacheck.validate",
    # statistics
    "stats": "pytacheck.stats.core",
    "statcheck": "pytacheck.stats.statcheck",
    # text
    "causal_relations": "pytacheck.text",
    "expand_text": "pytacheck.text",
    "extract_eq": "pytacheck.text",
    "extract_p_values": "pytacheck.text",
    "extract_tests": "pytacheck.text",
    "extract_urls": "pytacheck.text",
    "json_expand": "pytacheck.text",
    "search_text": "pytacheck.text",
    "text_expand": "pytacheck.text",
    "text_search": "pytacheck.text",
    # --- metacheck API (generated by scripts/sync_exports.py; do not edit) ---
    # reading and conversion
    "convert_bibr": "pytacheck.io.bibr_convert",
    "format_bib_authors": "pytacheck.io.bibr_convert",
    "convert": "pytacheck.io.convert",
    "papers_available": "pytacheck.io.corpus",
    "papers_load": "pytacheck.io.corpus",
    "papers_metadata": "pytacheck.io.corpus",
    "papers_remove": "pytacheck.io.corpus",
    "convert_grobid": "pytacheck.io.grobid",
    "grobid_to_bibr": "pytacheck.io.grobid",
    # bibliographic databases and registries
    "add_bib_match": "pytacheck.db.crossref",
    "crossref_doi": "pytacheck.db.crossref",
    "crossref_query": "pytacheck.db.crossref",
    "datacite_doi": "pytacheck.db.crossref",
    "openalex_doi": "pytacheck.db.crossref",
    "openalex_query": "pytacheck.db.crossref",
    "doi_clean": "pytacheck.db.doi",
    "doi_lookup": "pytacheck.db.doi",
    "doi_resolves": "pytacheck.db.doi",
    "doi_valid_format": "pytacheck.db.doi",
    "check_orcid": "pytacheck.db.orcid",
    "credit_roles": "pytacheck.db.orcid",
    "get_orcid": "pytacheck.db.orcid",
    "orcid_person": "pytacheck.db.orcid",
    "pubpeer_comments": "pytacheck.db.pubpeer",
    "regcheck_base_url": "pytacheck.db.regcheck",
    "regcheck_compare": "pytacheck.db.regcheck",
    "regcheck_tidy": "pytacheck.db.regcheck",
    "regcheck_setup_local": "pytacheck.db.regcheck_local",
    "regcheck_start_local": "pytacheck.db.regcheck_local",
    "regcheck_stop_local": "pytacheck.db.regcheck_local",
    "FLoRA": "pytacheck.db.replications",
    "FLoRA_date": "pytacheck.db.replications",
    "FLoRA_update": "pytacheck.db.replications",
    "retractionwatch": "pytacheck.db.retractionwatch",
    "rw": "pytacheck.db.retractionwatch",
    "rw_date": "pytacheck.db.retractionwatch",
    "rw_update": "pytacheck.db.retractionwatch",
    # LLMs
    "llm_cache": "pytacheck.llm.cache",
    "llm_cache_clear": "pytacheck.llm.cache",
    "llm": "pytacheck.llm.core",
    "llm_max_calls": "pytacheck.llm.core",
    "llm_max_tokens": "pytacheck.llm.core",
    "llm_model": "pytacheck.llm.core",
    "llm_model_list": "pytacheck.llm.core",
    "llm_reasoning": "pytacheck.llm.core",
    "llm_timeout": "pytacheck.llm.core",
    "llm_use": "pytacheck.llm.core",
    # repositories and archives
    "aspredicted_info": "pytacheck.archives.aspredicted",
    "aspredicted_links": "pytacheck.archives.aspredicted",
    "metacheck_cache_info": "pytacheck.archives.cache",
    "dataone_info": "pytacheck.archives.dataone",
    "dataone_links": "pytacheck.archives.dataone",
    "dataverse_file_download": "pytacheck.archives.dataverse",
    "dataverse_info": "pytacheck.archives.dataverse",
    "dataverse_links": "pytacheck.archives.dataverse",
    "dataverse_pat": "pytacheck.archives.dataverse",
    "download_repo_files": "pytacheck.archives.download",
    "repo_cache_clear": "pytacheck.archives.download",
    "repo_cache_dir": "pytacheck.archives.download",
    "repo_cache_size": "pytacheck.archives.download",
    "dryad_auth": "pytacheck.archives.dryad",
    "dryad_file_download": "pytacheck.archives.dryad",
    "dryad_info": "pytacheck.archives.dryad",
    "dryad_links": "pytacheck.archives.dryad",
    "dryad_pat": "pytacheck.archives.dryad",
    "dspace7_file_download": "pytacheck.archives.dspace7",
    "dspace7_links": "pytacheck.archives.dspace7",
    "figshare_file_download": "pytacheck.archives.figshare",
    "figshare_info": "pytacheck.archives.figshare",
    "figshare_links": "pytacheck.archives.figshare",
    "figshare_pat": "pytacheck.archives.figshare",
    "researchdata4tu_file_download": "pytacheck.archives.fourtu",
    "researchdata4tu_info": "pytacheck.archives.fourtu",
    "researchdata4tu_links": "pytacheck.archives.fourtu",
    "researchdata4tu_pat": "pytacheck.archives.fourtu",
    "fsd_info": "pytacheck.archives.fsd",
    "fsd_links": "pytacheck.archives.fsd",
    "github_files": "pytacheck.archives.github",
    "github_info": "pytacheck.archives.github",
    "github_languages": "pytacheck.archives.github",
    "github_links": "pytacheck.archives.github",
    "github_readme": "pytacheck.archives.github",
    "github_repo": "pytacheck.archives.github",
    "github_tree_files": "pytacheck.archives.github",
    "gitlab_links": "pytacheck.archives.gitlab",
    "gitlab_pat": "pytacheck.archives.gitlab",
    "gitlab_repo": "pytacheck.archives.gitlab",
    "gitlab_tree_files": "pytacheck.archives.gitlab",
    "repo_info_cache": "pytacheck.archives.info_cache",
    "repo_info_cache_clear": "pytacheck.archives.info_cache",
    "local_files": "pytacheck.archives.local",
    "mendeley_info": "pytacheck.archives.mendeley",
    "mendeley_links": "pytacheck.archives.mendeley",
    "osf_api_check": "pytacheck.archives.osf",
    "osf_cache_clear": "pytacheck.archives.osf",
    "osf_check_id": "pytacheck.archives.osf",
    "osf_delay": "pytacheck.archives.osf",
    "osf_file_download": "pytacheck.archives.osf",
    "osf_get_all_pages": "pytacheck.archives.osf",
    "osf_info": "pytacheck.archives.osf",
    "osf_links": "pytacheck.archives.osf",
    "osf_preprint_list": "pytacheck.archives.osf",
    "osf_type": "pytacheck.archives.osf",
    "osf_pat": "pytacheck.archives.osf_helpers",
    "osf_user_projects": "pytacheck.archives.osf_helpers",
    "dspace_links": "pytacheck.archives.psycharchives",
    "psycharchives_file_download": "pytacheck.archives.psycharchives",
    "psycharchives_info": "pytacheck.archives.psycharchives",
    "psycharchives_links": "pytacheck.archives.psycharchives",
    "rbox_file_download": "pytacheck.archives.researchbox",
    "rbox_info": "pytacheck.archives.researchbox",
    "rbox_links": "pytacheck.archives.researchbox",
    "reshare_file_download": "pytacheck.archives.reshare",
    "reshare_info": "pytacheck.archives.reshare",
    "reshare_links": "pytacheck.archives.reshare",
    "zenodo_file_download": "pytacheck.archives.zenodo",
    "zenodo_info": "pytacheck.archives.zenodo",
    "zenodo_links": "pytacheck.archives.zenodo",
    "zenodo_pat": "pytacheck.archives.zenodo_upload",
    "zenodo_upload": "pytacheck.archives.zenodo_upload",
    "zip_decision": "pytacheck.archives.zip_peek",
    "zip_peek": "pytacheck.archives.zip_peek",
    # file categories and naming
    "file_category": "pytacheck.fileinfo.category",
    "filetype": "pytacheck.fileinfo.category",
    "check_file_naming": "pytacheck.fileinfo.naming",
    # data files, codebooks and data checks
    "data_check_case_issues": "pytacheck.datacheck.checks",
    "data_check_colname": "pytacheck.datacheck.checks",
    "data_check_colname_collisions": "pytacheck.datacheck.checks",
    "data_check_constant": "pytacheck.datacheck.checks",
    "data_check_demographic": "pytacheck.datacheck.checks",
    "data_check_design_name": "pytacheck.datacheck.checks",
    "data_check_empty": "pytacheck.datacheck.checks",
    "data_check_is_behaverse": "pytacheck.datacheck.checks",
    "data_check_is_inquisit": "pytacheck.datacheck.checks",
    "data_check_is_jspsych": "pytacheck.datacheck.checks",
    "data_check_is_psychopy": "pytacheck.datacheck.checks",
    "data_check_is_qualtrics": "pytacheck.datacheck.checks",
    "data_check_numeric_in_text": "pytacheck.datacheck.checks",
    "data_check_outliers": "pytacheck.datacheck.checks",
    "data_check_pii_freetext": "pytacheck.datacheck.checks",
    "data_check_pii_geo": "pytacheck.datacheck.checks",
    "data_check_pii_name": "pytacheck.datacheck.checks",
    "data_check_pii_values": "pytacheck.datacheck.checks",
    "data_check_scale_values": "pytacheck.datacheck.checks",
    "data_check_spss_filter": "pytacheck.datacheck.checks",
    "data_check_whitespace": "pytacheck.datacheck.checks",
    "data_col_concept": "pytacheck.datacheck.checks",
    "data_col_facets": "pytacheck.datacheck.checks",
    "data_promote_header_row": "pytacheck.datacheck.checks",
    "data_strip_qualtrics_header": "pytacheck.datacheck.checks",
    "data_col_stats": "pytacheck.datacheck.columns",
    "data_col_type": "pytacheck.datacheck.columns",
    "match_column_labels": "pytacheck.datacheck.columns",
    "parse_codebook": "pytacheck.datacheck.columns",
    "parse_qsf": "pytacheck.datacheck.columns",
    "data_classify_files": "pytacheck.datacheck.files",
    "data_format": "pytacheck.datacheck.files",
    "data_group_llm": "pytacheck.datacheck.files",
    "data_is_manifest": "pytacheck.datacheck.files",
    "data_read_head": "pytacheck.datacheck.files",
    "data_study_roster": "pytacheck.datacheck.files",
    "manifest_merge": "pytacheck.datacheck.files",
    "text_peek": "pytacheck.datacheck.files",
    "txt_classify_content": "pytacheck.datacheck.files",
    # code checks
    "code_abs_path": "pytacheck.codecheck.core",
    "code_extract_py": "pytacheck.codecheck.core",
    "code_extract_qmd_py": "pytacheck.codecheck.core",
    "code_extract_r": "pytacheck.codecheck.core",
    "code_file_refs": "pytacheck.codecheck.core",
    "code_install_packages": "pytacheck.codecheck.core",
    "code_lang": "pytacheck.codecheck.core",
    "code_library_lines": "pytacheck.codecheck.core",
    "code_library_names": "pytacheck.codecheck.core",
    "code_line_stats": "pytacheck.codecheck.core",
    "code_packages": "pytacheck.codecheck.core",
    "code_parse_r": "pytacheck.codecheck.core",
    "code_read": "pytacheck.codecheck.core",
    "code_remove_comments": "pytacheck.codecheck.core",
    "code_setwd": "pytacheck.codecheck.core",
    # statistical software output
    "export_jasp_html": "pytacheck.statout.jasp",
    "import_jasp": "pytacheck.statout.jasp",
    "match_reported_output": "pytacheck.statout.match_reported",
    "export_mplus_html": "pytacheck.statout.mplus",
    "import_mplus_output": "pytacheck.statout.mplus",
    "export_omv_html": "pytacheck.statout.omv",
    "import_omv": "pytacheck.statout.omv",
    "read_r_output": "pytacheck.statout.r_output",
    "export_spv_html": "pytacheck.statout.spv",
    "import_spv": "pytacheck.statout.spv",
    "stat_output_json": "pytacheck.statout.stat_output",
    "stat_output_validate": "pytacheck.statout.stat_output",
    "stat_output_write": "pytacheck.statout.stat_output",
    "stat_results_long": "pytacheck.statout.stat_output",
    "read_stat_tables": "pytacheck.statout.stat_tables",
    "export_stata_smcl_html": "pytacheck.statout.stata",
    "import_stata_smcl": "pytacheck.statout.stata",
    "stato_type_column": "pytacheck.statout.stato_map",
    # report building blocks
    "cap_gate_count": "pytacheck.report.blocks",
    "collapse_section": "pytacheck.report.blocks",
    "format_ref": "pytacheck.report.blocks",
    "link": "pytacheck.report.blocks",
    "scroll_table": "pytacheck.report.blocks",
    # utilities
    "plural": "pytacheck._r.base",
    "coerce_paper": "pytacheck.papers.io",
    "is_paper": "pytacheck.papers.model",
    "is_paper_list": "pytacheck.papers.model",
    "load_schema": "pytacheck.papers.schema",
    "message": "pytacheck.utils",
    "online": "pytacheck.utils",
    "path_sanitize": "pytacheck.utils",
    "pb": "pytacheck.utils",
    "rep_if": "pytacheck.utils",
    # --- end of generated metacheck API ---
}

__all__ = ["UPSTREAM", "__version__", *sorted(_EXPORTS)]


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module 'pytacheck' has no attribute {name!r}")
    value = getattr(importlib.import_module(target), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))


if TYPE_CHECKING:  # pragma: no cover
    from pytacheck.config import cache_dir, email, verbose
    from pytacheck.io.bibr import chew
    from pytacheck.io.read import read
    from pytacheck.log import lastlog, logger, logpath
    from pytacheck.module import (
        ModuleError,
        ModuleOutput,
        ModuleSpec,
        get_prev_outputs,
        module,
        module_help,
        module_info,
        module_list,
        module_run,
        run_session,
        use,
    )
    from pytacheck.packs.check import CheckIssue, pack_check
    from pytacheck.packs.install import (
        pack_install,
        pack_list,
        pack_remove,
        pack_show,
        pack_update,
    )
    from pytacheck.packs.registry import refresh
    from pytacheck.packs.scaffold import module_template, pack_new
    from pytacheck.packs.stores import (
        store_add,
        store_list,
        store_remove,
        store_search,
        store_update,
    )
    from pytacheck.papers import (
        Paper,
        PaperList,
        PaperValidationError,
        demofile,
        demopaper,
        from_bibr,
        paper,
        paper_id,
        paper_table,
        paper_validate,
        paper_write,
        read_bibr,
        ref_table,
        test_paper,
    )
    from pytacheck.presets import preset, preset_list
    from pytacheck.provenance import ModuleChain, RunRecord, rerun, run_modules
    from pytacheck.report.blocks import report_table
    from pytacheck.report.emojis import emojis
    from pytacheck.report.report import (
        module_report,
        report,
        report_module_run,
        report_qmd,
        report_repository,
    )
    from pytacheck.stats.core import stats
    from pytacheck.stats.statcheck import statcheck
    from pytacheck.text import (
        causal_relations,
        expand_text,
        extract_eq,
        extract_p_values,
        extract_tests,
        extract_urls,
        json_expand,
        search_text,
        text_expand,
        text_search,
    )
    from pytacheck.validate import accuracy, validate


# --- metacheck API imports (generated by scripts/sync_exports.py; do not edit below) ---
if TYPE_CHECKING:  # pragma: no cover
    from pytacheck._r.base import plural
    from pytacheck.archives.aspredicted import aspredicted_info, aspredicted_links
    from pytacheck.archives.cache import metacheck_cache_info
    from pytacheck.archives.dataone import dataone_info, dataone_links
    from pytacheck.archives.dataverse import (
        dataverse_file_download,
        dataverse_info,
        dataverse_links,
        dataverse_pat,
    )
    from pytacheck.archives.download import (
        download_repo_files,
        repo_cache_clear,
        repo_cache_dir,
        repo_cache_size,
    )
    from pytacheck.archives.dryad import (
        dryad_auth,
        dryad_file_download,
        dryad_info,
        dryad_links,
        dryad_pat,
    )
    from pytacheck.archives.dspace7 import dspace7_file_download, dspace7_links
    from pytacheck.archives.figshare import (
        figshare_file_download,
        figshare_info,
        figshare_links,
        figshare_pat,
    )
    from pytacheck.archives.fourtu import (
        researchdata4tu_file_download,
        researchdata4tu_info,
        researchdata4tu_links,
        researchdata4tu_pat,
    )
    from pytacheck.archives.fsd import fsd_info, fsd_links
    from pytacheck.archives.github import (
        github_files,
        github_info,
        github_languages,
        github_links,
        github_readme,
        github_repo,
        github_tree_files,
    )
    from pytacheck.archives.gitlab import gitlab_links, gitlab_pat, gitlab_repo, gitlab_tree_files
    from pytacheck.archives.info_cache import repo_info_cache, repo_info_cache_clear
    from pytacheck.archives.local import local_files
    from pytacheck.archives.mendeley import mendeley_info, mendeley_links
    from pytacheck.archives.osf import (
        osf_api_check,
        osf_cache_clear,
        osf_check_id,
        osf_delay,
        osf_file_download,
        osf_get_all_pages,
        osf_info,
        osf_links,
        osf_preprint_list,
        osf_type,
    )
    from pytacheck.archives.osf_helpers import osf_pat, osf_user_projects
    from pytacheck.archives.psycharchives import (
        dspace_links,
        psycharchives_file_download,
        psycharchives_info,
        psycharchives_links,
    )
    from pytacheck.archives.researchbox import rbox_file_download, rbox_info, rbox_links
    from pytacheck.archives.reshare import reshare_file_download, reshare_info, reshare_links
    from pytacheck.archives.zenodo import zenodo_file_download, zenodo_info, zenodo_links
    from pytacheck.archives.zenodo_upload import zenodo_pat, zenodo_upload
    from pytacheck.archives.zip_peek import zip_decision, zip_peek
    from pytacheck.codecheck.core import (
        code_abs_path,
        code_extract_py,
        code_extract_qmd_py,
        code_extract_r,
        code_file_refs,
        code_install_packages,
        code_lang,
        code_library_lines,
        code_library_names,
        code_line_stats,
        code_packages,
        code_parse_r,
        code_read,
        code_remove_comments,
        code_setwd,
    )
    from pytacheck.datacheck.checks import (
        data_check_case_issues,
        data_check_colname,
        data_check_colname_collisions,
        data_check_constant,
        data_check_demographic,
        data_check_design_name,
        data_check_empty,
        data_check_is_behaverse,
        data_check_is_inquisit,
        data_check_is_jspsych,
        data_check_is_psychopy,
        data_check_is_qualtrics,
        data_check_numeric_in_text,
        data_check_outliers,
        data_check_pii_freetext,
        data_check_pii_geo,
        data_check_pii_name,
        data_check_pii_values,
        data_check_scale_values,
        data_check_spss_filter,
        data_check_whitespace,
        data_col_concept,
        data_col_facets,
        data_promote_header_row,
        data_strip_qualtrics_header,
    )
    from pytacheck.datacheck.columns import (
        data_col_stats,
        data_col_type,
        match_column_labels,
        parse_codebook,
        parse_qsf,
    )
    from pytacheck.datacheck.files import (
        data_classify_files,
        data_format,
        data_group_llm,
        data_is_manifest,
        data_read_head,
        data_study_roster,
        manifest_merge,
        text_peek,
        txt_classify_content,
    )
    from pytacheck.db.crossref import (
        add_bib_match,
        crossref_doi,
        crossref_query,
        datacite_doi,
        openalex_doi,
        openalex_query,
    )
    from pytacheck.db.doi import doi_clean, doi_lookup, doi_resolves, doi_valid_format
    from pytacheck.db.orcid import check_orcid, credit_roles, get_orcid, orcid_person
    from pytacheck.db.pubpeer import pubpeer_comments
    from pytacheck.db.regcheck import regcheck_base_url, regcheck_compare, regcheck_tidy
    from pytacheck.db.regcheck_local import (
        regcheck_setup_local,
        regcheck_start_local,
        regcheck_stop_local,
    )
    from pytacheck.db.replications import FLoRA, FLoRA_date, FLoRA_update
    from pytacheck.db.retractionwatch import retractionwatch, rw, rw_date, rw_update
    from pytacheck.fileinfo.category import file_category, filetype
    from pytacheck.fileinfo.naming import check_file_naming
    from pytacheck.io.bibr_convert import convert_bibr, format_bib_authors
    from pytacheck.io.convert import convert
    from pytacheck.io.corpus import papers_available, papers_load, papers_metadata, papers_remove
    from pytacheck.io.grobid import convert_grobid, grobid_to_bibr
    from pytacheck.llm.cache import llm_cache, llm_cache_clear
    from pytacheck.llm.core import (
        llm,
        llm_max_calls,
        llm_max_tokens,
        llm_model,
        llm_model_list,
        llm_reasoning,
        llm_timeout,
        llm_use,
    )
    from pytacheck.papers.io import coerce_paper
    from pytacheck.papers.model import is_paper, is_paper_list
    from pytacheck.papers.schema import load_schema
    from pytacheck.report.blocks import (
        cap_gate_count,
        collapse_section,
        format_ref,
        link,
        scroll_table,
    )
    from pytacheck.statout.jasp import export_jasp_html, import_jasp
    from pytacheck.statout.match_reported import match_reported_output
    from pytacheck.statout.mplus import export_mplus_html, import_mplus_output
    from pytacheck.statout.omv import export_omv_html, import_omv
    from pytacheck.statout.r_output import read_r_output
    from pytacheck.statout.spv import export_spv_html, import_spv
    from pytacheck.statout.stat_output import (
        stat_output_json,
        stat_output_validate,
        stat_output_write,
        stat_results_long,
    )
    from pytacheck.statout.stat_tables import read_stat_tables
    from pytacheck.statout.stata import export_stata_smcl_html, import_stata_smcl
    from pytacheck.statout.stato_map import stato_type_column
    from pytacheck.utils import message, online, path_sanitize, pb, rep_if
