# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.log import *  # noqa: F403

def __getattr__(name: str) -> Any: ...
