# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.fileinfo.category import file_category as file_category
from metacheck.fileinfo.category import filetype as filetype
from metacheck.fileinfo.naming import check_file_naming as check_file_naming
from metacheck.fileinfo.types import file_types as file_types

def __getattr__(name: str) -> Any: ...
