#!/usr/bin/env python3
"""Write the type stubs of the ``pytacheck`` alias package (``src/pytacheck/**/*.pyi``).

``import pytacheck`` is the old import name of metacheck (``metacheck._alias``).
At run time it forwards to metacheck; type checkers read these stubs instead:

* ``src/pytacheck/__init__.pyi``: every name of metacheck's ``_EXPORTS`` map,
  imported from the module that defines it, plus ``__version__``, ``UPSTREAM``
  and ``__all__``;
* one stub per public first-level submodule: ``<name>.pyi`` for a module,
  ``<name>/__init__.pyi`` for a subpackage. A subpackage with a lazy export map
  lists its names one by one (a star import would not re-export them); other
  modules are a star import of the real one.

Deeper submodules (``pytacheck.io.read``) are ``Any`` to type checkers: every
stub ends in ``__getattr__``, which also covers the names a module defines but
does not list in ``__all__`` (``pytacheck.config.PROJECT_CONFIG``, private
helpers). Code that needs their types imports metacheck. The script reads
``src/metacheck`` with ``ast`` and imports nothing from it.

    python scripts/alias_stubs.py           # write the stubs
    python scripts/alias_stubs.py --check   # exit 1 if a stub is missing, stale or extra

Run it after ``scripts/sync_exports.py`` or any change to an export map.
The output is sorted and formatted with ruff, so ruff must be installed.
"""

from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NEW, OLD = "metacheck", "pytacheck"
SRC = ROOT / "src" / NEW
OUT = ROOT / "src" / OLD

HEADER = f"""\
# Generated by scripts/alias_stubs.py from src/{NEW}; do not edit.
# {OLD} is the old import name of {NEW}. Deeper submodules are Any to type
# checkers here: import {NEW} for their types.
"""
GETATTR = "\ndef __getattr__(name: str) -> Any: ...\n"


class StubError(Exception):
    """The package cannot be described by the stubs (a name without a source)."""


def _parse(path: Path) -> ast.Module:
    return ast.parse(path.read_bytes(), filename=str(path))


def _export_map(tree: ast.Module) -> dict[str, str] | None:
    """The module's lazy export map (``name -> defining module``), if it has one.

    A lazy export map is a top-level dict whose keys are names and whose values
    are ``metacheck.*`` module names, in a module that defines ``__getattr__``.
    """
    has_getattr = any(isinstance(n, ast.FunctionDef) and n.name == "__getattr__" for n in tree.body)
    if not has_getattr:
        return None
    found: dict[str, str] = {}
    for node in tree.body:
        value = node.value if isinstance(node, ast.Assign | ast.AnnAssign) else None
        if not isinstance(value, ast.Dict) or not value.keys:
            continue
        pairs: dict[str, str] = {}
        for k, v in zip(value.keys, value.values, strict=True):
            if not (
                isinstance(k, ast.Constant)
                and isinstance(k.value, str)
                and isinstance(v, ast.Constant)
                and isinstance(v.value, str)
                and v.value.startswith(NEW + ".")
            ):
                break
            pairs[k.value] = v.value
        else:
            found.update(pairs)
    return found or None


def _static_all(tree: ast.Module) -> list[str]:
    """The string literals that ``__all__`` is built from (``sorted(MAP)`` adds nothing)."""
    names: list[str] = []
    for node in tree.body:
        target: ast.expr | None = None
        value: ast.expr | None = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target, value = node.targets[0], node.value
        elif isinstance(node, ast.AugAssign | ast.AnnAssign):
            target, value = node.target, node.value
        if not (isinstance(target, ast.Name) and target.id == "__all__" and value is not None):
            continue
        names.extend(
            n.value
            for n in ast.walk(value)
            if isinstance(n, ast.Constant) and isinstance(n.value, str)
        )
    return list(dict.fromkeys(names))


def _bindings(tree: ast.Module, modname: str) -> dict[str, str]:
    """Where each top-level public name of the module comes from (``name -> module``)."""
    out: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            for a in node.names:
                out.setdefault(a.asname or a.name, node.module)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            out.setdefault(node.name, modname)
        elif isinstance(node, ast.Assign | ast.AnnAssign):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for t in targets:
                if isinstance(t, ast.Name):
                    out.setdefault(t.id, modname)
    return out


def _import_lines(names: dict[str, str]) -> list[str]:
    """``from <module> import <name> as <name>`` for each name, sorted by module and name."""
    return [
        f"from {mod} import {name} as {name}"
        for name, mod in sorted(names.items(), key=lambda kv: (kv[1], kv[0]))
    ]


def _top_level() -> str:
    tree = _parse(SRC / "__init__.py")
    exports = _export_map(tree)
    if not exports:
        raise StubError(f"src/{NEW}/__init__.py has no _EXPORTS map")
    lines = [
        HEADER,
        "from typing import Any",
        "",
        f"from {NEW} import __all__ as __all__",
        f"from {NEW}._version import UPSTREAM as UPSTREAM",
        f"from {NEW}._version import __version__ as __version__",
        *_import_lines(exports),
        GETATTR,
    ]
    return "\n".join(lines)


def _submodule(path: Path, modname: str) -> str:
    tree = _parse(path)
    exports = _export_map(tree)
    lines = [HEADER, "from typing import Any", ""]
    if exports is None:
        lines.append(f"from {modname} import *  # noqa: F403")
    else:
        where = _bindings(tree, modname)
        names: dict[str, str] = {}
        for name in [*_static_all(tree), *exports]:
            if name in exports:
                names[name] = exports[name]
            elif name in where:
                names[name] = where[name]
            else:
                raise StubError(f"{modname}.{name} is in __all__ but is neither mapped nor bound")
        lines += _import_lines(names)
    # the other names (not in __all__, private, deeper submodules) are Any
    lines.append(GETATTR)
    return "\n".join(lines) + "\n"


def expected() -> dict[Path, str]:
    """Every stub file and its content, before formatting."""
    stubs = {OUT / "__init__.pyi": _top_level()}
    for entry in sorted(SRC.iterdir()):
        name = entry.name
        if name.startswith(("_", ".")):
            continue
        if entry.is_dir() and (entry / "__init__.py").is_file():
            stubs[OUT / name / "__init__.pyi"] = _submodule(entry / "__init__.py", f"{NEW}.{name}")
        elif entry.is_file() and entry.suffix == ".py":
            stubs[OUT / f"{entry.stem}.pyi"] = _submodule(entry, f"{NEW}.{entry.stem}")
    return stubs


def _ruff(path: Path, text: str) -> str:
    """*text* with its imports sorted and formatted as ruff does for *path*."""
    base = [sys.executable, "-m", "ruff"]
    rel = path.relative_to(ROOT).as_posix()
    for args in (["check", "--select", "I", "--fix", "-q"], ["format", "-q"]):
        done = subprocess.run(
            [*base, *args, "--stdin-filename", rel, "-"],
            cwd=ROOT,
            input=text,
            capture_output=True,
            text=True,
            check=False,
        )
        if done.returncode != 0:
            raise StubError(f"ruff {args[0]} failed on {rel}: {done.stderr.strip()}")
        text = done.stdout
    return text


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if out of date")
    ns = ap.parse_args(argv)
    try:
        want = {p: _ruff(p, t) for p, t in expected().items()}
    except (StubError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    have = {p for p in OUT.rglob("*.pyi") if "__pycache__" not in p.parts}
    stale = sorted(p for p, t in want.items() if not p.is_file() or p.read_bytes() != t.encode())
    extra = sorted(have - set(want))
    for p in stale:
        print(f"{'stale' if ns.check else 'wrote'} {p.relative_to(ROOT).as_posix()}")
    for p in extra:
        print(f"{'extra' if ns.check else 'removed'} {p.relative_to(ROOT).as_posix()}")
    if ns.check:
        if stale or extra:
            print("the pytacheck stubs are out of date: run python scripts/alias_stubs.py")
            return 1
        return 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(want[p].encode())
    for p in extra:
        p.unlink()
        if p.parent != OUT and not any(p.parent.iterdir()):
            p.parent.rmdir()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
