"""Generate the tables of docs/CODEMAP.md: where each part of metacheck lives in Python.

    uv run python scripts/codemap.py           # rewrite the generated blocks
    uv run python scripts/codemap.py --check   # exit 1 if docs/CODEMAP.md is out of date

docs/CODEMAP.md is hand-written prose with generated blocks between
``<!-- BEGIN codemap:<name> ... -->`` and ``<!-- END codemap:<name> -->``:

* ``pin``: the metacheck commit the map describes (``parity/UPSTREAM.toml``);
* ``modules``: one row per check, from ``upstream/metacheck/inst/modules`` and
  ``src/metacheck/modules``;
* ``functions``: every function metacheck exports (``NAMESPACE`` ``export()``
  and ``S3method()``), grouped by the R file that defines it, in file order;
* ``python-only``: top-level ``metacheck`` exports with no R counterpart.

The sources are the files the port already keeps up to date:
``porting/symbols.json`` plus the ``[functions]`` of ``porting/map/*.toml``
(each R function's Python home), the ``[files]`` of those maps (the Python files
of each R file, and the test area that owns it), ``porting/skip.toml`` (not
ported by design), ``parity/cases`` and ``parity/divergences`` (which functions
and checks are compared with R, and which ``docs/UPSTREAM_ISSUES.md`` entries
their marks cite) and the status snapshot read by ``metacheck.status``.

``--check`` also fails when a hand-written part has fallen behind: an R package
from ``DESCRIPTION`` missing from the package table, a ``data/`` or ``inst/``
entry missing from the data section, a subpackage of ``src/metacheck`` missing
from the layout table, or a relative link that does not resolve.

``tests/foundation/test_codemap.py`` runs the same check.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import json
import keyword
import re
import sys
import tomllib
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "CODEMAP.md"
UP = ROOT / "upstream" / "metacheck"
NAMESPACE = UP / "NAMESPACE"
SRC = ROOT / "src" / "metacheck"

#: S3 methods porting/symbols.json does not list (its scanner skips names like ``[.x``)
EXTRA_SYMBOLS = {
    "[.scivrs_paperlist": "metacheck.papers.model:PaperList.__getitem__",
}

_REF = re.compile(r"\A([UD])([1-9]\d*)\Z")
_DEF = re.compile(r"^(`[^`]+`|[A-Za-z.][A-Za-z0-9._]*)\s*(?:<-|=)\s*(.*)$")
_ALIAS = re.compile(r"^([A-Za-z.][A-Za-z0-9._]*)\s*(?:#.*)?$")


def _begin(name: str) -> str:
    return f"<!-- BEGIN codemap:{name} (generated by scripts/codemap.py; do not edit) -->\n"


def _end(name: str) -> str:
    return f"<!-- END codemap:{name} -->\n"


# -- inputs ----------------------------------------------------------------------------


def r_exports() -> tuple[list[str], list[str]]:
    """``(export() names, S3method() names as generic.class)`` from NAMESPACE."""
    text = NAMESPACE.read_text(encoding="utf-8")
    exports = [e.strip('"`') for e in re.findall(r"^export\(([^)]+)\)", text, re.MULTILINE)]
    methods = [
        f"{g.strip(chr(34))}.{c}"
        for g, c in re.findall(r"^S3method\(([^,]+),([^)]+)\)", text, re.MULTILINE)
    ]
    return exports, methods


def r_definitions(names: set[str]) -> dict[str, tuple[str, int, str | None]]:
    """``name -> (R file, line, alias target or None)`` for top-level definitions."""
    out: dict[str, tuple[str, int, str | None]] = {}
    for path in sorted((UP / "R").glob("*.R")):
        rel = f"R/{path.name}"
        for i, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            m = _DEF.match(line)
            if not m:
                continue
            name = m.group(1).strip("`")
            if name not in names or name in out:
                continue
            alias = _ALIAS.match(m.group(2).strip())  # `rw <- retractionwatch`
            target = alias.group(1) if alias and alias.group(1) != "function" else None
            out[name] = (rel, i, target)
    return out


def load_maps() -> tuple[dict[str, str], dict[str, list[str]], dict[str, list[str]]]:
    """``(symbols, R file -> Python files, R file -> areas)``.

    *symbols* is porting/symbols.json updated with the maps' ``[functions]``
    (as scripts/port_status.py does), as ``R name -> "module:name"``.
    """
    raw: dict[str, dict[str, Any]] = json.loads(
        (ROOT / "porting" / "symbols.json").read_text(encoding="utf-8")
    )
    symbols = {k: str(v.get("python", "")) for k, v in raw.items()}
    files: dict[str, list[str]] = defaultdict(list)
    areas: dict[str, list[str]] = defaultdict(list)
    for toml in sorted((ROOT / "porting" / "map").glob("*.toml")):
        data = tomllib.loads(toml.read_text(encoding="utf-8"))
        symbols.update(data.get("functions", {}))
        for r_file, py in data.get("files", {}).items():
            areas[r_file].append(toml.stem)
            for p in py if isinstance(py, list) else [py]:
                if p.startswith("src/") and p not in files[r_file]:
                    files[r_file].append(p)
    for name, target in EXTRA_SYMBOLS.items():
        symbols.setdefault(name, target)
    return symbols, files, areas


def load_skip() -> dict[str, str]:
    data = tomllib.loads((ROOT / "porting" / "skip.toml").read_text(encoding="utf-8"))
    return {str(k): str(v) for k, v in data.get("skip", {}).items()}


def _ref_key(ref: str) -> tuple[str, int]:
    m = _REF.match(ref)
    assert m, ref
    return (m.group(1), int(m.group(2)))


@dataclass
class Coverage:
    """What the parity cases compare with R, and the register entries their marks cite."""

    areas: dict[str, set[str]] = field(default_factory=lambda: defaultdict(set))
    refs: dict[str, set[str]] = field(default_factory=lambda: defaultdict(set))


def parity_coverage() -> tuple[Coverage, Coverage]:
    """``(by R function, by module)`` over every case in parity/cases."""
    sys.path.insert(0, str(ROOT))
    from parity import cases as pc

    divs = pc.read_divergences()
    by_fn, by_mod = Coverage(), Coverage()
    for path in pc.iter_case_files():
        data = pc.load_yaml(path) or {}
        area = str(data.get("area") or path.stem)
        for spec in data.get("cases") or []:
            if not isinstance(spec, dict):
                continue
            marks = [spec.get("known_divergence")]
            marks += [m.div for m in divs.matching(area, f"{area}/{spec.get('id')}")]
            refs = {
                str(m["ref"])
                for m in marks
                if isinstance(m, dict) and _REF.match(str(m.get("ref", "")))
            }
            if spec.get("module"):
                target, name = by_mod, str(spec["module"])
            elif spec.get("r"):
                target, name = by_fn, re.sub(r"^metacheck:::?", "", str(spec["r"]))
            else:
                continue
            target.areas[name].add(area)
            target.refs[name] |= refs
    return by_fn, by_mod


# -- Python side -----------------------------------------------------------------------


def py_name(r_name: str) -> str:
    """The Python name scripts/porting_symbols.py gives an R name by default."""
    internal = r_name.startswith(".")
    name = re.sub(r"[^A-Za-z0-9_]", "_", r_name.lstrip("."))
    if internal:
        name = "_" + name
    if keyword.iskeyword(name) or name in (
        "print",
        "format",
        "type",
        "id",
        "input",
        "open",
        "filter",
    ):
        name += "_"
    return name


def resolve(target: str) -> Any | None:
    """The object ``module:attr.path`` names, or ``None``."""
    module, _, attr = target.partition(":")
    if not module.startswith("metacheck") or not attr:
        return None
    try:
        obj: Any = importlib.import_module(module)
    except Exception:
        return None
    for part in attr.split("."):
        if not hasattr(obj, part):
            return None
        obj = getattr(obj, part)
    return obj


def module_file(module: str) -> Path | None:
    """The source file of a ``metacheck`` module (a file or a package's __init__)."""
    rel = Path(*module.split("."))
    for cand in (ROOT / "src" / rel.with_suffix(".py"), ROOT / "src" / rel / "__init__.py"):
        if cand.is_file():
            return cand
    return None


def defining_file(target: str, obj: Any) -> Path | None:
    """Where *obj* is defined: its own module when it is a metacheck one, else the target's."""
    own = getattr(inspect.unwrap(obj), "__module__", None) if obj is not None else None
    for module in (own, target.partition(":")[0]):
        if isinstance(module, str) and module.startswith("metacheck"):
            path = module_file(module)
            if path is not None:
                return path
    return None


def link(path: Path, text: str | None = None) -> str:
    """A markdown link from docs/ to *path* (a file or folder in this repository)."""
    rel = Path("..") / path.relative_to(ROOT)
    return f"[{text or path.relative_to(ROOT).as_posix()}]({rel.as_posix()})"


def short_py(path: str) -> str:
    """``src/metacheck/db/doi.py`` -> ``db/doi.py``."""
    return path.removeprefix("src/metacheck/")


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def refs_text(refs: set[str]) -> str:
    return ", ".join(sorted(refs, key=_ref_key)) if refs else ""


def first_line(obj: Any) -> str:
    doc = inspect.getdoc(obj) or ""
    para = " ".join(doc.strip().split("\n\n", 1)[0].split())
    para = re.sub(r":[a-z]+:`~?([^`]+)`", r"`\1`", para)  # Sphinx roles
    return para.replace("``", "`")


# -- blocks ----------------------------------------------------------------------------


def block_pin() -> str:
    up = tomllib.loads((ROOT / "parity" / "UPSTREAM.toml").read_text(encoding="utf-8"))
    info = up["upstream"]
    repo, commit = str(info["repository"]).rstrip("/"), str(info["commit"])
    pr = info.get("pull_request")
    branch = f"`{info.get('branch', 'dev')}`" + (
        f" plus pull request [#{pr}]({repo}/pull/{pr})" if pr else ""
    )
    return (
        f"This map describes metacheck {info.get('version', '')} ({branch}) at commit\n"
        f"[`{commit[:12]}`]({repo}/tree/{commit}). R paths below are relative to that\n"
        f"repository, which is checked out in this one as the submodule `upstream/metacheck`.\n"
    )


def _area_names(areas: set[str], own: list[str]) -> str:
    """Parity areas as plain names (a ``*_review`` area folded into its base), the
    areas that own the code first."""
    base = {a.removesuffix("_review") for a in areas}
    first = [a for a in own if a in base]
    return ", ".join([*first, *sorted(base - set(first))])


def _test_dirs(name: str, areas: list[str]) -> list[Path]:
    """The ``tests/<area>`` folders of *areas* whose test files mention *name*."""
    word = re.compile(rf"\b{re.escape(name)}\b")
    out = []
    for area in areas:
        folder = ROOT / "tests" / area
        if not folder.is_dir():
            continue
        if any(word.search(p.read_text(encoding="utf-8")) for p in folder.rglob("test_*.py")):
            out.append(folder)
    return out


def block_modules(files: dict[str, list[str]], areas: dict[str, list[str]], cov: Coverage) -> str:
    from metacheck.module import module_find
    from metacheck.status import snapshot, status

    registry = snapshot()
    r_mods = sorted(p.stem for p in (UP / "inst" / "modules").glob("*.R"))
    py_mods = sorted(p.stem for p in (SRC / "modules").glob("*.py") if not p.stem.startswith("_"))
    names = sorted(set(r_mods) | set(py_mods))
    rows = [
        "| Check | R file | Python | Tests | Parity areas | Status | Recorded differences |",
        "|---|---|---|---|---|---|---|",
    ]
    py_only = 0
    for name in names:
        r_file = f"inst/modules/{name}.R"
        main = f"src/metacheck/modules/{name}.py"
        py_files = [main] if (ROOT / main).is_file() else []
        py_files += [p for p in files.get(r_file, []) if p not in py_files]
        py_cell = "<br>".join(link(ROOT / p, short_py(p)) for p in py_files) or "not ported"
        if name in r_mods:
            r_cell = f"`{r_file}`"
        else:
            r_cell = "Python only"
            py_only += 1
        title = ""
        label = ""
        if name in py_mods:
            spec = module_find(name)
            title = f"<br>{cell(spec.title)}" if spec.title else ""
            label = status(f"metacheck::{name}", registry=registry).label
        mod_areas = sorted(a for a in areas.get(r_file, []) if a.startswith("mod_"))
        mod_areas += sorted(a for a in areas.get(r_file, []) if not a.startswith("mod_"))
        tests = _test_dirs(name, mod_areas)
        test_cell = "<br>".join(link(t, t.relative_to(ROOT).as_posix()) for t in tests) or "—"
        rows.append(
            f"| `{name}`{title} | {r_cell} | {py_cell} | {test_cell} | "
            f"{_area_names(cov.areas.get(name, set()), mod_areas) or '—'} | {label or '—'} | "
            f"{refs_text(cov.refs.get(name, set())) or '—'} |"
        )
    ported = sum(1 for n in r_mods if n in py_mods)
    head = (
        f"{len(r_mods)} checks in metacheck, {ported} of them ported; "
        f"{py_only} Python-only checks.\n\n"
    )
    return head + "\n".join(rows) + "\n"


@dataclass
class FnRow:
    r_name: str
    line: int
    python: str
    target: str
    notes: list[str]
    parity: bool
    refs: set[str]
    status: str  # ported, skip, missing


def _fn_rows(
    symbols: dict[str, str], skip: dict[str, str], cov: Coverage
) -> tuple[dict[str, list[FnRow]], list[str], list[str]]:
    exports, methods = r_exports()
    defs = r_definitions(set(exports) | set(methods))
    by_file: dict[str, list[FnRow]] = defaultdict(list)
    for r_name in [*exports, *methods]:
        r_file, line, alias = defs.get(r_name, ("(not found)", 0, None))
        notes: list[str] = []
        if r_name in methods:
            notes.append("S3 method.")
        if alias:
            notes.append(f"Alias of `{alias}()`.")
        target = symbols.get(r_name, "")
        obj = None if r_name in skip else resolve(target)
        if r_name in skip:
            state, python = "skip", "—"
            notes.append(f"Not ported by design: {skip[r_name]}")
        elif obj is None:
            state, python = "missing", "—"
            notes.append("Not ported yet.")
        else:
            state = "ported"
            path = defining_file(target, obj)
            python = link(path, f"`{target}`") if path else f"`{target}`"
            attr = target.partition(":")[2]
            if r_name not in methods and attr != py_name(r_name):
                notes.append(f"Python name differs: `{attr}`.")
        by_file[r_file].append(
            FnRow(
                r_name=r_name,
                line=line,
                python=python,
                target=target,
                notes=notes,
                parity=bool(cov.areas.get(r_name)),
                refs=cov.refs.get(r_name, set()),
                status=state,
            )
        )
    return by_file, exports, methods


def block_functions(
    symbols: dict[str, str],
    skip: dict[str, str],
    files: dict[str, list[str]],
    areas: dict[str, list[str]],
    cov: Coverage,
) -> str:
    by_file, exports, methods = _fn_rows(symbols, skip, cov)
    rows = [r for rs in by_file.values() for r in rs]
    n_ported = sum(r.status == "ported" for r in rows)
    n_skip = sum(r.status == "skip" for r in rows)
    n_missing = sum(r.status == "missing" for r in rows)
    n_renamed = sum(any(n.startswith("Python name differs") for n in r.notes) for r in rows)
    n_parity = sum(r.parity for r in rows)
    out = [
        f"metacheck exports {len(exports)} functions and {len(methods)} S3 methods. "
        f"Ported: {n_ported}. Not ported by design: {n_skip}. Not ported yet: {n_missing}. "
        f"Ported under a different Python name: {n_renamed}. "
        f"Called directly by parity cases: {n_parity}.\n",
    ]
    for r_file in sorted(by_file, key=lambda f: (f == "(not found)", f)):
        out.append(f"\n### `{r_file}`\n\n")
        py = files.get(r_file, [])
        if py:
            out.append("Python: " + ", ".join(link(ROOT / p, short_py(p)) for p in py) + ".")
        else:
            out.append("Python: none.")
        test_dirs = [ROOT / "tests" / a for a in areas.get(r_file, [])]
        test_dirs = [t for t in test_dirs if t.is_dir()]
        if test_dirs:
            out.append(
                " Tests: " + ", ".join(link(t, t.relative_to(ROOT).as_posix()) for t in test_dirs)
            )
            out.append(".")
        out.append("\n\n| R function | Python | Parity | Differences | Notes |\n")
        out.append("|---|---|---|---|---|\n")
        for r in sorted(by_file[r_file], key=lambda r: (r.line, r.r_name)):
            shown = f"`{r.r_name}`" if r.r_name.startswith("%") else f"`{r.r_name}()`"
            out.append(
                f"| {cell(shown)} | {r.python} | {'yes' if r.parity else '—'} | "
                f"{refs_text(r.refs) or '—'} | {cell(' '.join(r.notes))} |\n"
            )
    return "".join(out)


def block_python_only(symbols: dict[str, str]) -> str:
    import metacheck

    from_r = {t.partition(":")[2] for t in symbols.values()}
    rows = []
    for name, module in sorted(metacheck._EXPORTS.items(), key=lambda kv: (kv[1], kv[0])):
        if name in from_r:
            continue
        obj = resolve(f"{module}:{name}")
        path = defining_file(f"{module}:{name}", obj)
        where = link(path, f"`{module}:{name}`") if path else f"`{module}:{name}`"
        rows.append(f"| `{name}` | {where} | {cell(first_line(obj))} |")
    head = (
        f"{len(rows)} top-level names of the `metacheck` package have no metacheck "
        "counterpart.\n\n| Name | Python | What it is |\n|---|---|---|\n"
    )
    return head + "\n".join(rows) + "\n"


# -- the document ----------------------------------------------------------------------


def _replace(source: str, name: str, body: str) -> str:
    begin, end = _begin(name), _end(name)
    head, sep, rest = source.partition(begin)
    if not sep:
        raise SystemExit(f"{DOC}: marker not found: {begin.strip()}")
    _, sep, tail = rest.partition(end)
    if not sep:
        raise SystemExit(f"{DOC}: marker not found: {end.strip()}")
    return head + begin + body + end + tail


def generate(source: str) -> str:
    """*source* (docs/CODEMAP.md) with its generated blocks brought up to date."""
    symbols, files, areas = load_maps()
    skip = load_skip()
    by_fn, by_mod = parity_coverage()
    source = _replace(source, "pin", block_pin())
    source = _replace(source, "modules", block_modules(files, areas, by_mod))
    source = _replace(source, "functions", block_functions(symbols, skip, files, areas, by_fn))
    return _replace(source, "python-only", block_python_only(symbols))


def _section(source: str, heading: str) -> str:
    m = re.search(rf"^## {re.escape(heading)}\n(.*?)(?=^## |\Z)", source, re.M | re.S)
    if not m:
        raise SystemExit(f"{DOC}: section not found: ## {heading}")
    return m.group(1)


def _description_packages() -> list[str]:
    text = (UP / "DESCRIPTION").read_text(encoding="utf-8")
    out: list[str] = []
    for fld in ("Imports", "Suggests"):
        m = re.search(rf"^{fld}:(.*?)(?=^\S)", text, re.M | re.S)
        if m:
            out += [re.sub(r"\(.*?\)", "", p).strip() for p in m.group(1).split(",")]
    return [p for p in out if p]


def problems(source: str) -> list[str]:
    """Hand-written parts of *source* that have fallen behind the code."""
    out: list[str] = []
    packages = _section(source, "R package dependencies")
    listed = set()
    for row in re.findall(r"^\|([^|\n]*)\|", packages, re.M):
        listed |= set(re.findall(r"`([A-Za-z0-9.]+)`", row))
    out += [
        f"package table: no row for {p} (DESCRIPTION)"
        for p in _description_packages()
        if p not in listed
    ]
    data = _section(source, "Data and resources")
    wanted = [f"data/{p.name}" for p in sorted((UP / "data").glob("*"))]
    wanted += [f"inst/{p.name}" for p in sorted((UP / "inst").iterdir()) if p.name[0].isalpha()]
    out += [f"data section: {w} is not mentioned" for w in wanted if w not in data]
    layout = _section(source, "How the Python package is laid out")
    out += [
        f"layout table: `{p.name}/` is not mentioned"
        for p in sorted(SRC.iterdir())
        if (p / "__init__.py").is_file() and f"`{p.name}/`" not in layout
    ]
    for target in re.findall(r"\]\(([^)\s]+)\)", source):
        if re.match(r"[a-z]+:", target) or target.startswith("#"):
            continue
        if not (DOC.parent / target.split("#", 1)[0]).exists():
            out.append(f"broken link: {target}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the doc is out of date")
    args = ap.parse_args()
    sys.path.insert(0, str(ROOT / "src"))
    source = DOC.read_text(encoding="utf-8")
    new = generate(source)
    issues = problems(new)
    for issue in issues:
        print(f"docs/CODEMAP.md: {issue}", file=sys.stderr)
    if args.check:
        if new != source:
            print("docs/CODEMAP.md is out of date: run scripts/codemap.py", file=sys.stderr)
            return 1
        return 1 if issues else 0
    if new != source:
        DOC.write_text(new, encoding="utf-8", newline="\n")
        print("docs/CODEMAP.md updated")
    return 1 if issues else 0


if __name__ == "__main__":
    sys.exit(main())
