"""Write docs/STATUS.md: how much of metacheck is ported and parity-tested.

    uv run python scripts/port_status.py

A function counts as ported when its canonical Python target (porting/symbols.json)
can be imported. Parity numbers come from running the parity suite.
"""

from __future__ import annotations

import importlib
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def resolve(target: str) -> bool:
    module, _, name = target.partition(":")
    try:
        mod = importlib.import_module(module)
    except Exception:
        return False
    return hasattr(mod, name)


def main() -> None:
    from parity.__main__ import check_case
    from parity.cases import load_cases

    symbols = json.loads((ROOT / "porting" / "symbols.json").read_text(encoding="utf-8"))
    by_file: dict[str, list[tuple[str, bool]]] = defaultdict(list)
    for name, entry in symbols.items():
        rfile = entry.get("file") or "(other)"
        by_file[rfile].append((name, resolve(entry["python"])))

    area_stats: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for case in load_cases():
        status, _, _ = check_case(case)
        area_stats[case.area][status] += 1
        area_stats[case.area]["total"] += 1

    total = sum(len(v) for v in by_file.values())
    done = sum(ok for v in by_file.values() for _, ok in v)
    modules = [(n, ok) for f, v in by_file.items() if f.startswith("inst/modules") for n, ok in v]
    lines = [
        "# Porting status",
        "",
        "Generated by `scripts/port_status.py`.",
        "",
        f"- **R functions ported:** {done} / {total} ({100 * done / max(total, 1):.0f}%)",
        f"- **Modules ported:** {sum(ok for _, ok in modules)} / {len(modules)}",
        f"- **Parity cases:** {sum(s['pass'] for s in area_stats.values())} passing of "
        f"{sum(s['total'] for s in area_stats.values())}",
        "",
        "## Parity by area",
        "",
        "| area | cases | pass | fail | error | missing golden | known divergence |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for area in sorted(area_stats):
        s = area_stats[area]
        lines.append(
            f"| {area} | {s['total']} | {s['pass']} | {s['fail']} | {s['error']} | {s['missing']} | {s['xfail']} |"
        )
    lines += ["", "## R source files", "", "| file | ported | missing |", "|---|---:|---|"]
    for rfile in sorted(by_file):
        items = by_file[rfile]
        missing = [n for n, ok in items if not ok]
        shown = ", ".join(f"`{m}`" for m in missing[:12]) + (" ..." if len(missing) > 12 else "")
        lines.append(f"| `{rfile}` | {len(items) - len(missing)}/{len(items)} | {shown} |")
    (ROOT / "docs" / "STATUS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{done}/{total} functions, {len(area_stats)} parity areas -> docs/STATUS.md")


if __name__ == "__main__":
    main()
