"""Regenerate the metacheck-API block of ``src/metacheck/__init__.py``.

Every function metacheck exports (``upstream/metacheck/NAMESPACE``) that pytacheck
has ported is exported lazily from the top-level package, under the Python name
and location that ``porting/symbols.json`` gives it. A function counts as ported
when its module imports and defines it. Internal R helpers that metacheck
exports for its modules (``.osf_info`` and the like -> ``_osf_info``) stay in
their modules: underscore names are never top-level exports.

Names the hand-written part of ``_EXPORTS`` already lists are left alone, so
the core API (reading, papers, the module system, text, stats, reports) keeps
its curated grouping and the generated block holds everything else.

    uv run python scripts/sync_exports.py           # rewrite the block
    uv run python scripts/sync_exports.py --check   # exit 1 if it is out of date

``tests/foundation/test_exports.py`` runs the same check, so integrating a port
lane without re-running this script fails the test suite.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INIT = ROOT / "src" / "metacheck" / "__init__.py"
NAMESPACE = ROOT / "upstream" / "metacheck" / "NAMESPACE"
SYMBOLS = ROOT / "porting" / "symbols.json"
LINE_LENGTH = 100

BEGIN = "    # --- metacheck API (generated by scripts/sync_exports.py; do not edit) ---\n"
END = "    # --- end of generated metacheck API ---\n"
#: everything after this line is generated: a TYPE_CHECKING block for type checkers/IDEs
IMPORTS_MARKER = (
    "# --- metacheck API imports (generated by scripts/sync_exports.py; do not edit below) ---\n"
)

#: section comment for each package (in this order)
SECTIONS = {
    "metacheck.io": "reading and conversion",
    "metacheck.db": "bibliographic databases and registries",
    "metacheck.llm": "LLMs",
    "metacheck.archives": "repositories and archives",
    "metacheck.fileinfo": "file categories and naming",
    "metacheck.datacheck": "data files, codebooks and data checks",
    "metacheck.codecheck": "code checks",
    "metacheck.statout": "statistical software output",
    "metacheck.repro": "computational reproducibility",
    "metacheck.report": "report building blocks",
    "metacheck": "utilities",
}


def _section(module: str) -> str:
    parts = module.split(".")
    for n in range(len(parts), 0, -1):
        key = ".".join(parts[:n])
        if key in SECTIONS:
            return key
    return "metacheck"


def r_exports() -> list[str]:
    text = NAMESPACE.read_text(encoding="utf-8")
    return [e.strip('"`') for e in re.findall(r"^export\(([^)]+)\)", text, re.MULTILINE)]


def ported_exports() -> dict[str, str]:
    """``{python_name: module}`` for every ported, public metacheck export."""
    symbols = json.loads(SYMBOLS.read_text(encoding="utf-8"))
    out: dict[str, str] = {}
    for r_name in r_exports():
        info = symbols.get(r_name)
        if not info:
            continue
        module, _, name = info["python"].partition(":")
        if not name.isidentifier() or name.startswith("_"):
            continue
        try:
            mod = importlib.import_module(module)
        except ImportError:
            continue
        if hasattr(mod, name):
            out[name] = module
    return out


def _split(source: str, begin: str, end: str) -> tuple[str, str, str]:
    head, sep, rest = source.partition(begin)
    if not sep:
        raise SystemExit(f"{INIT}: marker not found: {begin.strip()}")
    body, sep, tail = rest.partition(end)
    if not sep:
        raise SystemExit(f"{INIT}: marker not found: {end.strip()}")
    return head, body, tail


def _curated(source: str) -> set[str]:
    """Names in ``_EXPORTS`` outside the generated block."""
    head, _, tail = _split(source, BEGIN, END)
    block = head.split("_EXPORTS: dict[str, str] = {", 1)[1] + tail.split("\n}\n", 1)[0]
    return set(re.findall(r'^    "(\w+)": "[\w.]+",$', block, re.MULTILINE))


def _import_line(module: str, names: list[str]) -> str:
    one = f"    from {module} import {', '.join(names)}"
    if len(one) <= LINE_LENGTH:
        return one + "\n"
    return f"    from {module} import (\n" + "".join(f"        {n},\n" for n in names) + "    )\n"


def render(exports: dict[str, str]) -> tuple[str, str]:
    by_module: dict[str, list[str]] = defaultdict(list)
    for name, module in exports.items():
        by_module[module].append(name)
    order = list(SECTIONS)
    modules = sorted(by_module, key=lambda m: (order.index(_section(m)), m))
    entries, imports = [], []
    current = None
    for module in modules:
        names = sorted(by_module[module], key=lambda n: (n.lower(), n))
        section = _section(module)
        if section != current:
            entries.append(f"    # {SECTIONS[section]}\n")
            current = section
        entries += [f'    "{n}": "{module}",\n' for n in names]
        imports.append(_import_line(module, sorted(names)))
    block = "\n\nif TYPE_CHECKING:  # pragma: no cover\n" + "".join(imports) if imports else ""
    return "".join(entries), block


def generate(source: str) -> str:
    curated = _curated(source)
    exports = {n: m for n, m in ported_exports().items() if n not in curated}
    entries, imports = render(exports)
    head, _, tail = _split(source, BEGIN, END)
    source = head + BEGIN + entries + END + tail
    head, sep, _ = source.partition(IMPORTS_MARKER)
    if not sep:
        raise SystemExit(f"{INIT}: marker not found: {IMPORTS_MARKER.strip()}")
    return _ruff(head + IMPORTS_MARKER + imports.lstrip("\n"))


def _ruff(source: str) -> str:
    """Sort the generated imports and format the file the way the repository's ruff does."""
    name = str(INIT.relative_to(ROOT))
    for args in (["check", "--fix", "--select", "I", "--quiet"], ["format", "--quiet"]):
        res = subprocess.run(
            [sys.executable, "-m", "ruff", *args, "--stdin-filename", name, "-"],
            input=source,
            capture_output=True,
            text=True,
            cwd=ROOT,
            check=False,
        )
        if res.returncode not in (0, 1) or not res.stdout:
            raise SystemExit(f"ruff {args[0]} failed: {res.stderr.strip()}")
        source = res.stdout
    return source


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="only report whether it is current")
    ns = parser.parse_args(argv)
    sys.path.insert(0, str(ROOT / "src"))
    source = INIT.read_text(encoding="utf-8")
    new = generate(source)
    if new == source:
        print("metacheck/__init__.py exports are up to date")
        return 0
    if ns.check:
        print("metacheck/__init__.py exports are out of date: run scripts/sync_exports.py")
        return 1
    INIT.write_text(new, encoding="utf-8")
    print(f"updated {INIT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
