# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.io.bibr_convert import convert_bibr as convert_bibr
from metacheck.io.bibr_convert import format_bib_authors as format_bib_authors
from metacheck.io.convert import convert as convert
from metacheck.io.corpus import papers_available as papers_available
from metacheck.io.corpus import papers_load as papers_load
from metacheck.io.corpus import papers_metadata as papers_metadata
from metacheck.io.corpus import papers_remove as papers_remove
from metacheck.io.grobid import convert_grobid as convert_grobid
from metacheck.io.grobid import grobid_to_bibr as grobid_to_bibr
from metacheck.io.read import read as read

def __getattr__(name: str) -> Any: ...
