# Generated by scripts/alias_stubs.py from src/metacheck; do not edit.
# pytacheck is the old import name of metacheck. Deeper submodules are Any to type
# checkers here: import metacheck for their types.

from typing import Any

from metacheck.db.crossref import add_bib_match as add_bib_match
from metacheck.db.crossref import crossref_doi as crossref_doi
from metacheck.db.crossref import crossref_query as crossref_query
from metacheck.db.crossref import datacite_doi as datacite_doi
from metacheck.db.crossref import openalex_doi as openalex_doi
from metacheck.db.crossref import openalex_query as openalex_query
from metacheck.db.databases import miscite as miscite
from metacheck.db.doi import doi_clean as doi_clean
from metacheck.db.doi import doi_lookup as doi_lookup
from metacheck.db.doi import doi_resolves as doi_resolves
from metacheck.db.doi import doi_valid_format as doi_valid_format
from metacheck.db.orcid import check_orcid as check_orcid
from metacheck.db.orcid import credit_roles as credit_roles
from metacheck.db.orcid import get_orcid as get_orcid
from metacheck.db.orcid import orcid_person as orcid_person
from metacheck.db.pubpeer import pubpeer_comments as pubpeer_comments
from metacheck.db.regcheck import RegCheckError as RegCheckError
from metacheck.db.regcheck import regcheck_base_url as regcheck_base_url
from metacheck.db.regcheck import regcheck_compare as regcheck_compare
from metacheck.db.regcheck import regcheck_tidy as regcheck_tidy
from metacheck.db.regcheck_local import regcheck_setup_local as regcheck_setup_local
from metacheck.db.regcheck_local import regcheck_start_local as regcheck_start_local
from metacheck.db.regcheck_local import regcheck_stop_local as regcheck_stop_local
from metacheck.db.replications import FLoRA as FLoRA
from metacheck.db.replications import FLoRA_date as FLoRA_date
from metacheck.db.replications import FLoRA_update as FLoRA_update
from metacheck.db.retractionwatch import rw as rw
from metacheck.db.retractionwatch import rw_date as rw_date
from metacheck.db.retractionwatch import rw_update as rw_update

def __getattr__(name: str) -> Any: ...
