"""RegCheck Preregistration Comparison (port of ``inst/modules/reg_check.R``).

The module takes the preregistrations found by ``prereg_check`` (from a
chained run, or by running ``prereg_check`` itself) and compares each one
with the full paper text through a RegCheck server
(:func:`pytacheck.db.regcheck.regcheck_compare`), one LLM judgement per
comparison dimension.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pandas as pd

from pytacheck._r import as_character, bind_rows, gsub, is_na, plural, trimws
from pytacheck.module import module
from pytacheck.report import collapse_section, format_ref, scroll_table

__all__ = ["prereg_row_text", "reg_check"]

# R: format_ref(vandenAkker2024) / format_ref(Lakens2024), rendered by R's bibentry html style.
_VAN_DEN_AKKER_2024 = (
    "van den Akker O, Bakker M, van Assen M, Pennington C, Verweij L, Elsherif M, Claesen A, "
    "Gaillard S, Yeung S, Frankenberger J, Krautter K, Cockcroft J, Kreuer K, Evans T, "
    "Heppel F, Schoch S, Korbmacher M, Yamada Y, Albayrak-Aydemir N, Wicherts J (2024). "
    "&ldquo;The potential of preregistration in psychology: Assessing preregistration "
    "producibility and preregistration-study consistency.&rdquo; "
    "<em>Psychological Methods</em>. "
    '<a href="https://doi.org/10.1037/met0000687">doi:10.1037/met0000687</a>.'
)
_LAKENS_2024 = (
    "Lakens, Daniël (2024). &ldquo;When and How to Deviate From a Preregistration.&rdquo; "
    "<em>Collabra: Psychology</em>, <b>10</b>(1), 117094. "
    '<a href="https://doi.org/10.1525/collabra.117094">doi:10.1525/collabra.117094</a>.'
)

_DISCLAIMER = (
    "These judgements are generated by a large language model: treat them as pointers for "
    "manual checking, not as conclusions, and always verify them against the original "
    "documents."
)
_CREDITS = (
    "RegCheck was developed by Jamie Cummins (<https://github.com/JamieCummins/regcheck>); "
    "the local Ollama server bundled in metacheck is inspired by the Ollama integration work "
    "of Matilda Fogato (<https://github.com/Matilda03/regcheck-fork>)."
)

#: judgement_label: RegCheck's judgements as report labels
_JUDGEMENT_LABEL = {"yes": "deviation", "no": "consistent", "missing": "unclear"}

#: strip_refs(): RegCheck's [PAPER_0001, REG_0002] quote references
_REFS = r"\s*\[[A-Z_0-9,; ]+\]"

#: prereg_row_text(): columns that are not preregistration content
_SKIP = ("paper_id", "link", "ia_url")


def _chr(values: Sequence[Any]) -> list[str | None]:
    """``as.character()`` of a column (``None`` for ``NA``)."""
    return [as_character(v) for v in values]


def _col(df: pd.DataFrame, name: str) -> list[Any]:
    """``df$name`` as a list of cells (R: ``NULL`` for a missing column -> ``[]``)."""
    if name not in df.columns:
        return []
    return [None if is_na(v) else v for v in df[name].tolist()]


def _strip_refs(values: Sequence[Any]) -> list[str | None]:
    """``strip_refs()``: drop RegCheck's bracketed quote references."""
    return list(gsub(_REFS, "", _chr(values)))


def _cell_text(value: Any) -> str | None:
    """``as.character(val)[[1]]`` of one cell (list cells as R deparses them)."""
    if isinstance(value, list | tuple):
        if len(value) == 1 and not isinstance(value[0], list | tuple):
            value = value[0]
        elif len(value) == 0:
            return "NULL"
        else:
            from pytacheck.report.render import deparse

            return " ".join(line.strip() for line in deparse(list(value)))
    return as_character(value)


def prereg_row_text(row: pd.DataFrame | pd.Series | dict[str, Any]) -> str:
    """Flatten a preregistration row to text for RegCheck.

    Port of ``prereg_row_text()`` in ``inst/modules/reg_check.R``: one
    ``"field_name\\nvalue"`` block per non-empty field (``paper_id``, ``link``
    and ``ia_url`` are skipped), joined with blank lines, so RegCheck receives
    the full structured content of the preregistration.
    """
    if isinstance(row, pd.DataFrame):
        cells = {c: row[c].tolist() for c in dict.fromkeys(row.columns)}
    elif isinstance(row, pd.Series):
        cells = {k: [v] for k, v in row.items()}
    else:
        cells = {k: v if isinstance(v, list | tuple) else [v] for k, v in row.items()}
    out: list[str] = []
    for nm, values in cells.items():
        if nm in _SKIP:
            continue
        if values is None or len(values) == 0:
            continue
        val = _cell_text(values[0])
        if val is None or not trimws(val):
            continue
        out.append(f"{nm}\n{val}")
    return "\n\n".join(out)


def _paper_ids(paper: Any) -> list[str]:
    """``paper_id(paper)``."""
    from pytacheck.papers.tables import paper_id

    return paper_id(paper)


def _summary(paper: Any, value: float) -> pd.DataFrame:
    """``data.frame(paper_id = paper_id(paper), regcheck_deviations = value)``."""
    ids = _paper_ids(paper)
    if not ids:
        # an empty paper list: paper_id() is NULL, and data.frame() does not
        # recycle the length-one column to zero rows
        raise ValueError("arguments imply differing number of rows: 0, 1")
    return pd.DataFrame(
        {
            "paper_id": pd.Series(ids, dtype="string"),
            "regcheck_deviations": pd.Series([value] * len(ids), dtype="float64"),
        }
    )


def _full_text(paper: Any) -> str:
    """``paste(p$text$text, collapse = " ")``."""
    if paper is None:
        return ""
    text = paper["text"]
    if text is None or "text" not in text.columns:
        return ""
    return " ".join("NA" if is_na(t) else str(t) for t in text["text"].tolist())


def _count(j: Sequence[str | None], value: str) -> Any:
    """``sum(j == value)``: ``NA`` when any judgement is ``NA``."""
    if any(v is None for v in j):
        return pd.NA
    return sum(v == value for v in j)


def _fmt_d(n: Any) -> str:
    """``sprintf("%d", n)`` (``"NA"`` for ``NA``)."""
    return "NA" if n is pd.NA or n is None else f"{n:d}"


def _plural(n: Any) -> str:
    """``plural(n)`` pasted by ``sprintf("%s")`` (``ifelse()`` keeps ``NA``)."""
    return "NA" if n is pd.NA or n is None else plural(n)


@module(
    title="RegCheck Preregistration Comparison",
    description="""
        Compare the preregistrations of a paper with the paper itself using
        RegCheck, an LLM-based tool that judges, dimension by dimension, whether
        the paper is consistent with what was preregistered.
    """,
    details="""
        The RegCheck module builds on the Preregistration Check module: it takes
        the preregistration content retrieved by `prereg_check` and sends it,
        together with the full paper text, to a
        [RegCheck](https://github.com/JamieCummins/regcheck) server. RegCheck
        compares the two documents on a set of dimensions (sample size,
        hypotheses, exclusion criteria, etc.) and judges for each dimension
        whether the paper deviates from the preregistration ("yes"), is consistent
        with it ("no"), or whether there is insufficient information to tell
        ("missing").

        You can chain the modules so the preregistrations are only retrieved once:
        `paper |> module_run("prereg_check") |> module_run("reg_check")`. If you
        run `reg_check` on its own, it runs `prereg_check` for you first.

        By default the comparison uses the locally running
        RegCheck server bundled inside metacheck with Ollama
        (`client = "ollama"`, `http://localhost:8000`), so no text leaves your
        machine. Set `client` to "groq", "openai" or "deepseek" to use the hosted
        RegCheck app instead; note that this sends the full paper and
        preregistration text to that server and the corresponding LLM provider.
        All RegCheck servers (including a local one) require an API token in the
        `REGCHECK_API_TOKEN` environment variable (see `?regcheck_compare`).

        Each comparison makes one LLM call per dimension and can take several
        minutes per preregistration. The judgements are generated by a large
        language model and are presented as pointers for manual checking, never as
        automated conclusions.
    """,
    keywords=["method"],
    requires=["network", "llm"],
    author=["Daniel Lakens <D.Lakens@tue.nl>"],
    params={
        "paper": "a paper object or paperlist object",
        "client": 'the LLM client RegCheck should use: "ollama" (local, default), "groq", '
        '"openai", or "deepseek"',
        "base_url": "the base URL of the RegCheck server (defaults to http://localhost:8000 "
        "for ollama, the hosted RegCheck app otherwise)",
        "dimensions": "optional data frame with columns `dimension` and `definition` to "
        "override RegCheck's default comparison dimensions",
    },
)
def reg_check(
    paper: Any,
    client: str = "ollama",
    base_url: str | None = None,
    dimensions: pd.DataFrame | None = None,
) -> dict[str, Any]:
    """Port of inst/modules/reg_check.R::reg_check().

    Compares every (unique) preregistration found by ``prereg_check`` with the
    full text of its paper via RegCheck and reports the per-dimension
    judgements (deviation / consistent / unclear) for manual checking. A
    chained ``prereg_check`` output is reused; otherwise ``prereg_check`` is
    run first. Failed comparisons are skipped; if all fail the light is
    ``"error"``.
    """
    from pytacheck.module import get_prev_outputs, module_run
    from pytacheck.papers.model import PaperList
    from pytacheck.utils import message

    # get prereg info ----
    # from a chained prereg_check run, or by running prereg_check now
    prereg_info = get_prev_outputs("prereg_check", "table")
    if prereg_info is None:
        prereg_out = module_run(paper, "prereg_check")
        prereg_info = prereg_out.table

    ## no preregistrations ----
    if prereg_info is None or len(prereg_info) == 0:
        return {
            "traffic_light": "na",
            "summary_text": "No preregistrations were found to compare with the paper.",
            "na_replace": 0,
            "summary_table": _summary(paper, 0.0),
        }

    # papers often link the same preregistration more than once, which gives
    # duplicate rows in prereg_info; compare each unique prereg only once
    missing = [c for c in ("paper_id", "id") if c not in prereg_info.columns]
    if missing:
        # R: prereg_info[, c("paper_id", "id")] on prereg_check's tibble
        raise ValueError(
            f"Can't subset columns that don't exist.\n✖ Column `{missing[0]}` doesn't exist."
        )
    dup = prereg_info.duplicated(subset=["paper_id", "id"], keep="first").to_numpy()
    prereg_info = prereg_info.loc[~dup].reset_index(drop=True)

    # compare each prereg with its paper ----
    from pytacheck.db import regcheck

    rc_list: list[pd.DataFrame] = []
    rc_error: str | None = None
    ids = _col(prereg_info, "id")
    pids = _col(prereg_info, "paper_id")
    for i in range(len(prereg_info)):
        pid = pids[i]
        if pid is None:
            pid = _paper_ids(paper)[0]
        if isinstance(paper, PaperList):
            # R: paper[[pid]] is NULL for an ID that is not in the list
            p = paper[pid] if pid in paper.names else None
        else:
            p = paper
        full_text = _full_text(p)
        prereg_text = prereg_row_text(prereg_info.iloc[[i]])
        rid = "NA" if ids[i] is None else as_character(ids[i])

        message(
            "RegCheck: comparing preregistration ",
            rid,
            " with paper ",
            pid,
            " (this can take several minutes)",
        )

        try:
            # looked up on the module so tests can mock regcheck_compare()
            rc = regcheck.regcheck_compare(
                full_text,
                prereg_text,
                client=client,
                base_url=base_url,
                dimensions=dimensions,
            )
        except Exception as e:  # R: tryCatch(error = function(e) e)
            rc_error = str(e)
            message("RegCheck comparison failed for preregistration ", rid, ": ", rc_error)
            continue

        if len(rc) > 0:
            rc = rc.copy()
            rc["prereg_id"] = pd.Series([ids[i]] * len(rc), index=rc.index, dtype="string")
            rc["paper_id"] = pd.Series([pid] * len(rc), index=rc.index, dtype="string")
            rc_list.append(rc)

    ## all comparisons failed ----
    if not rc_list:
        # no na_replace here: a failed check is unknown (NA), not zero
        n = len(prereg_info)
        err = f": {rc_error}" if rc_error is not None else ""
        return {
            "traffic_light": "error",
            "summary_text": (
                f"We found {n} preregistration{plural(n)}, but the RegCheck comparison failed{err}."
            ),
            "summary_table": _summary(paper, float("nan")),
        }

    regcheck_table = bind_rows(rc_list).reset_index(drop=True)
    regcheck_table.attrs = {}

    # traffic light ----
    # judgements are LLM-generated information for human review, never an
    # automated verdict, so the light stays informational
    tl = "info"

    # summary counts ----
    judgements = _chr(_col(regcheck_table, "deviation_judgement"))
    j: list[str | None] = [None if v is None else trimws(v).lower() for v in judgements]
    paper_col = _chr(_col(regcheck_table, "paper_id"))
    prereg_col = _chr(_col(regcheck_table, "prereg_id"))
    if len(j) != len(paper_col):
        # data.frame(paper_id = ..., j = NULL-derived character(0))
        raise ValueError(f"arguments imply differing number of rows: {len(paper_col)}, {len(j)}")
    n_dev = _count(j, "yes")
    n_unclear = _count(j, "missing")
    n_prereg_compared = len(dict.fromkeys(prereg_col))

    # summarise(.by = "paper_id"): groups in first-appearance order
    groups: dict[str | None, list[str | None]] = {}
    for pid, jj in zip(paper_col, j, strict=True):
        groups.setdefault(pid, []).append(jj)
    summary_table = pd.DataFrame(
        {
            "paper_id": pd.Series(list(groups), dtype="string"),
            "regcheck_deviations": pd.array(
                [_count(g, "yes") for g in groups.values()], dtype="Int64"
            ),
            "regcheck_consistent": pd.array(
                [_count(g, "no") for g in groups.values()], dtype="Int64"
            ),
            "regcheck_unclear": pd.array(
                [_count(g, "missing") for g in groups.values()], dtype="Int64"
            ),
        }
    )

    # summary text ----
    n_rows = len(regcheck_table)
    summary_text = (
        f"RegCheck compared the paper with {n_prereg_compared} "
        f"preregistration{plural(n_prereg_compared)} on {n_rows} dimension{plural(n_rows)}, "
        f"and flagged {_fmt_d(n_dev)} potential deviation{_plural(n_dev)} "
        f"({_fmt_d(n_unclear)} dimension{_plural(n_unclear)} not specified in the "
        "preregistration)."
    )

    # report ----
    report_intro = f"{summary_text} {_DISCLAIMER}"

    prereg_sections: list[Any] = []
    for rid in dict.fromkeys(prereg_col):
        mask = [r == rid for r in prereg_col]
        sub = regcheck_table.loc[mask]
        raw = _col(sub, "deviation_judgement")
        sub_j = [None if v is None else trimws(as_character(v)).lower() for v in raw]
        labels = [_JUDGEMENT_LABEL.get(v) if v is not None else None for v in sub_j]
        labels = [
            lab if lab is not None else as_character(orig)
            for lab, orig in zip(labels, raw, strict=True)
        ]
        dimension = pd.Series(_chr(_col(sub, "dimension")), dtype="string")
        judgement_table = pd.DataFrame(
            {
                "dimension": dimension,
                "judgement": pd.Series(labels, dtype="string"),
                "explanation": pd.Series(
                    _strip_refs(_col(sub, "deviation_information")), dtype="string"
                ),
            }
        )
        evidence_table = pd.DataFrame(
            {
                "dimension": dimension,
                **{
                    col: pd.Series(_strip_refs(_col(sub, col)), dtype="string")
                    for col in ("paper_summary", "prereg_summary", "paper_quotes", "prereg_quotes")
                },
            }
        )
        label = "NA" if rid is None else rid
        evidence = collapse_section(
            scroll_table(evidence_table, maxrows=5), f"RegCheck evidence for {label}"
        )
        prereg_sections.extend(
            [
                f"Comparison with preregistration {label}:",
                scroll_table(judgement_table),
                *(evidence if isinstance(evidence, list) else [evidence]),
            ]
        )

    ## guidance ----
    guidance = [
        _CREDITS,
        "For metascientific articles demonstrating the rate of deviations from "
        "preregistrations, see:",
        format_ref(_VAN_DEN_AKKER_2024),
        "For educational material on how to report deviations from preregistrations, see:",
        format_ref(_LAKENS_2024),
    ]

    report = [report_intro, *prereg_sections, collapse_section(guidance)]

    # return a list ----
    return {
        "table": regcheck_table,
        "summary_table": summary_table,
        "na_replace": 0,
        "traffic_light": tl,
        "report": report,
        "summary_text": summary_text,
    }
