"""pytacheck: check research outputs for best practices.

A Python-native, parity-tested port of ScienceVerse's `metacheck
<https://github.com/scienceverse/metacheck>`_ R package, built to work
hand in hand with `bibr <https://bibr.org>`_.

.. code-block:: python

    import metacheck as pc

    paper = pc.read("paper.json")            # bibr JSON, Grobid XML, or a PDF via bibr
    out = pc.module_run(paper, "all_p_values")
    out.table

Public names are imported lazily so ``import metacheck`` stays fast.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, Any

from metacheck._version import UPSTREAM, __version__

# name -> module that defines it. Keep sorted by module.
_EXPORTS: dict[str, str] = {
    # configuration & logging
    "cache_dir": "metacheck.config",
    "email": "metacheck.config",
    "verbose": "metacheck.config",
    "lastlog": "metacheck.log",
    "logger": "metacheck.log",
    "logpath": "metacheck.log",
    # reading
    "read": "metacheck.io.read",
    "chew": "metacheck.io.bibr",
    # module system
    "ModuleError": "metacheck.module",
    "ModuleOutput": "metacheck.module",
    "ModuleSpec": "metacheck.module",
    "get_prev_outputs": "metacheck.module",
    "module": "metacheck.module",
    "module_help": "metacheck.module",
    "module_info": "metacheck.module",
    "module_list": "metacheck.module",
    "module_run": "metacheck.module",
    "run_session": "metacheck.module",
    "use": "metacheck.module",
    # packs & presets (module system v2; metacheck.packs is only imported on use)
    "CheckIssue": "metacheck.packs.check",
    "pack_check": "metacheck.packs.check",
    "pack_install": "metacheck.packs.install",
    "pack_list": "metacheck.packs.install",
    "pack_remove": "metacheck.packs.install",
    "pack_show": "metacheck.packs.install",
    "pack_update": "metacheck.packs.install",
    "refresh": "metacheck.packs.registry",
    "module_template": "metacheck.packs.scaffold",
    "pack_new": "metacheck.packs.scaffold",
    "store_add": "metacheck.packs.stores",
    "store_list": "metacheck.packs.stores",
    "store_remove": "metacheck.packs.stores",
    "store_search": "metacheck.packs.stores",
    "store_update": "metacheck.packs.stores",
    "preset": "metacheck.presets",
    "preset_list": "metacheck.presets",
    # run records and reproducibility
    "ModuleChain": "metacheck.provenance",
    "RunRecord": "metacheck.provenance",
    "rerun": "metacheck.provenance",
    "run_modules": "metacheck.provenance",
    # papers
    "Paper": "metacheck.papers",
    "PaperList": "metacheck.papers",
    "PaperValidationError": "metacheck.papers",
    "demofile": "metacheck.papers",
    "demopaper": "metacheck.papers",
    "from_bibr": "metacheck.papers",
    "paper": "metacheck.papers",
    "paper_id": "metacheck.papers",
    "paper_table": "metacheck.papers",
    "paper_validate": "metacheck.papers",
    "paper_write": "metacheck.papers",
    "read_bibr": "metacheck.papers",
    "ref_table": "metacheck.papers",
    "test_paper": "metacheck.papers",
    # bundled tables (metacheck's datasets, as functions)
    "emojis": "metacheck.report.emojis",
    "file_types": "metacheck.fileinfo.types",
    "scales": "metacheck.datacheck.scales",
    "tasks": "metacheck.datacheck.tasks",
    # reports and validation
    "module_report": "metacheck.report.report",
    "report": "metacheck.report.report",
    "report_module_run": "metacheck.report.report",
    "report_qmd": "metacheck.report.report",
    "report_repository": "metacheck.report.report",
    "report_table": "metacheck.report.blocks",
    "accuracy": "metacheck.validate",
    "validate": "metacheck.validate",
    # statistics
    "stats": "metacheck.stats.core",
    "statcheck": "metacheck.stats.statcheck",
    # text
    "causal_relations": "metacheck.text",
    "expand_text": "metacheck.text",
    "extract_eq": "metacheck.text",
    "extract_p_values": "metacheck.text",
    "extract_tests": "metacheck.text",
    "extract_urls": "metacheck.text",
    "json_expand": "metacheck.text",
    "search_text": "metacheck.text",
    "text_expand": "metacheck.text",
    "text_search": "metacheck.text",
    # --- metacheck API (generated by scripts/sync_exports.py; do not edit) ---
    # reading and conversion
    "convert_bibr": "metacheck.io.bibr_convert",
    "format_bib_authors": "metacheck.io.bibr_convert",
    "convert": "metacheck.io.convert",
    "papers_available": "metacheck.io.corpus",
    "papers_load": "metacheck.io.corpus",
    "papers_metadata": "metacheck.io.corpus",
    "papers_remove": "metacheck.io.corpus",
    "convert_grobid": "metacheck.io.grobid",
    "grobid_to_bibr": "metacheck.io.grobid",
    # bibliographic databases and registries
    "add_bib_match": "metacheck.db.crossref",
    "crossref_doi": "metacheck.db.crossref",
    "crossref_query": "metacheck.db.crossref",
    "datacite_doi": "metacheck.db.crossref",
    "openalex_doi": "metacheck.db.crossref",
    "openalex_query": "metacheck.db.crossref",
    "doi_clean": "metacheck.db.doi",
    "doi_lookup": "metacheck.db.doi",
    "doi_resolves": "metacheck.db.doi",
    "doi_valid_format": "metacheck.db.doi",
    "check_orcid": "metacheck.db.orcid",
    "credit_roles": "metacheck.db.orcid",
    "get_orcid": "metacheck.db.orcid",
    "orcid_person": "metacheck.db.orcid",
    "pubpeer_comments": "metacheck.db.pubpeer",
    "regcheck_base_url": "metacheck.db.regcheck",
    "regcheck_compare": "metacheck.db.regcheck",
    "regcheck_tidy": "metacheck.db.regcheck",
    "regcheck_setup_local": "metacheck.db.regcheck_local",
    "regcheck_start_local": "metacheck.db.regcheck_local",
    "regcheck_stop_local": "metacheck.db.regcheck_local",
    "FLoRA": "metacheck.db.replications",
    "FLoRA_date": "metacheck.db.replications",
    "FLoRA_update": "metacheck.db.replications",
    "retractionwatch": "metacheck.db.retractionwatch",
    "rw": "metacheck.db.retractionwatch",
    "rw_date": "metacheck.db.retractionwatch",
    "rw_update": "metacheck.db.retractionwatch",
    # LLMs
    "llm_cache": "metacheck.llm.cache",
    "llm_cache_clear": "metacheck.llm.cache",
    "llm": "metacheck.llm.core",
    "llm_max_calls": "metacheck.llm.core",
    "llm_max_tokens": "metacheck.llm.core",
    "llm_model": "metacheck.llm.core",
    "llm_model_list": "metacheck.llm.core",
    "llm_reasoning": "metacheck.llm.core",
    "llm_timeout": "metacheck.llm.core",
    "llm_use": "metacheck.llm.core",
    # repositories and archives
    "aspredicted_info": "metacheck.archives.aspredicted",
    "aspredicted_links": "metacheck.archives.aspredicted",
    "metacheck_cache_info": "metacheck.archives.cache",
    "dataone_info": "metacheck.archives.dataone",
    "dataone_links": "metacheck.archives.dataone",
    "dataverse_file_download": "metacheck.archives.dataverse",
    "dataverse_info": "metacheck.archives.dataverse",
    "dataverse_links": "metacheck.archives.dataverse",
    "dataverse_pat": "metacheck.archives.dataverse",
    "download_repo_files": "metacheck.archives.download",
    "repo_cache_clear": "metacheck.archives.download",
    "repo_cache_dir": "metacheck.archives.download",
    "repo_cache_size": "metacheck.archives.download",
    "dryad_auth": "metacheck.archives.dryad",
    "dryad_file_download": "metacheck.archives.dryad",
    "dryad_info": "metacheck.archives.dryad",
    "dryad_links": "metacheck.archives.dryad",
    "dryad_pat": "metacheck.archives.dryad",
    "dspace7_file_download": "metacheck.archives.dspace7",
    "dspace7_links": "metacheck.archives.dspace7",
    "figshare_file_download": "metacheck.archives.figshare",
    "figshare_info": "metacheck.archives.figshare",
    "figshare_links": "metacheck.archives.figshare",
    "figshare_pat": "metacheck.archives.figshare",
    "researchdata4tu_file_download": "metacheck.archives.fourtu",
    "researchdata4tu_info": "metacheck.archives.fourtu",
    "researchdata4tu_links": "metacheck.archives.fourtu",
    "researchdata4tu_pat": "metacheck.archives.fourtu",
    "fsd_info": "metacheck.archives.fsd",
    "fsd_links": "metacheck.archives.fsd",
    "github_files": "metacheck.archives.github",
    "github_info": "metacheck.archives.github",
    "github_languages": "metacheck.archives.github",
    "github_links": "metacheck.archives.github",
    "github_readme": "metacheck.archives.github",
    "github_repo": "metacheck.archives.github",
    "github_tree_files": "metacheck.archives.github",
    "gitlab_links": "metacheck.archives.gitlab",
    "gitlab_pat": "metacheck.archives.gitlab",
    "gitlab_repo": "metacheck.archives.gitlab",
    "gitlab_tree_files": "metacheck.archives.gitlab",
    "repo_info_cache": "metacheck.archives.info_cache",
    "repo_info_cache_clear": "metacheck.archives.info_cache",
    "local_files": "metacheck.archives.local",
    "mendeley_info": "metacheck.archives.mendeley",
    "mendeley_links": "metacheck.archives.mendeley",
    "osf_api_check": "metacheck.archives.osf",
    "osf_cache_clear": "metacheck.archives.osf",
    "osf_check_id": "metacheck.archives.osf",
    "osf_delay": "metacheck.archives.osf",
    "osf_file_download": "metacheck.archives.osf",
    "osf_get_all_pages": "metacheck.archives.osf",
    "osf_info": "metacheck.archives.osf",
    "osf_links": "metacheck.archives.osf",
    "osf_preprint_list": "metacheck.archives.osf",
    "osf_type": "metacheck.archives.osf",
    "osf_pat": "metacheck.archives.osf_helpers",
    "osf_user_projects": "metacheck.archives.osf_helpers",
    "dspace_links": "metacheck.archives.psycharchives",
    "psycharchives_file_download": "metacheck.archives.psycharchives",
    "psycharchives_info": "metacheck.archives.psycharchives",
    "psycharchives_links": "metacheck.archives.psycharchives",
    "rbox_file_download": "metacheck.archives.researchbox",
    "rbox_info": "metacheck.archives.researchbox",
    "rbox_links": "metacheck.archives.researchbox",
    "reshare_file_download": "metacheck.archives.reshare",
    "reshare_info": "metacheck.archives.reshare",
    "reshare_links": "metacheck.archives.reshare",
    "zenodo_file_download": "metacheck.archives.zenodo",
    "zenodo_info": "metacheck.archives.zenodo",
    "zenodo_links": "metacheck.archives.zenodo",
    "zenodo_pat": "metacheck.archives.zenodo_upload",
    "zenodo_upload": "metacheck.archives.zenodo_upload",
    "zip_decision": "metacheck.archives.zip_peek",
    "zip_peek": "metacheck.archives.zip_peek",
    "zip_peek_cache_clear": "metacheck.archives.zip_peek_cache",
    # file categories and naming
    "file_category": "metacheck.fileinfo.category",
    "filetype": "metacheck.fileinfo.category",
    "check_file_naming": "metacheck.fileinfo.naming",
    # data files, codebooks and data checks
    "data_check_case_issues": "metacheck.datacheck.checks",
    "data_check_colname": "metacheck.datacheck.checks",
    "data_check_colname_collisions": "metacheck.datacheck.checks",
    "data_check_constant": "metacheck.datacheck.checks",
    "data_check_demographic": "metacheck.datacheck.checks",
    "data_check_design_name": "metacheck.datacheck.checks",
    "data_check_empty": "metacheck.datacheck.checks",
    "data_check_is_behaverse": "metacheck.datacheck.checks",
    "data_check_is_inquisit": "metacheck.datacheck.checks",
    "data_check_is_jspsych": "metacheck.datacheck.checks",
    "data_check_is_psychopy": "metacheck.datacheck.checks",
    "data_check_is_qualtrics": "metacheck.datacheck.checks",
    "data_check_numeric_in_text": "metacheck.datacheck.checks",
    "data_check_outliers": "metacheck.datacheck.checks",
    "data_check_pii_freetext": "metacheck.datacheck.checks",
    "data_check_pii_geo": "metacheck.datacheck.checks",
    "data_check_pii_name": "metacheck.datacheck.checks",
    "data_check_pii_values": "metacheck.datacheck.checks",
    "data_check_scale_values": "metacheck.datacheck.checks",
    "data_check_spss_filter": "metacheck.datacheck.checks",
    "data_check_whitespace": "metacheck.datacheck.checks",
    "data_col_concept": "metacheck.datacheck.checks",
    "data_col_facets": "metacheck.datacheck.checks",
    "data_promote_header_row": "metacheck.datacheck.checks",
    "data_strip_qualtrics_header": "metacheck.datacheck.checks",
    "data_col_stats": "metacheck.datacheck.columns",
    "data_col_type": "metacheck.datacheck.columns",
    "match_column_labels": "metacheck.datacheck.columns",
    "parse_codebook": "metacheck.datacheck.columns",
    "parse_qsf": "metacheck.datacheck.columns",
    "data_classify_files": "metacheck.datacheck.files",
    "data_format": "metacheck.datacheck.files",
    "data_group_llm": "metacheck.datacheck.files",
    "data_is_manifest": "metacheck.datacheck.files",
    "data_read_head": "metacheck.datacheck.files",
    "data_study_roster": "metacheck.datacheck.files",
    "manifest_merge": "metacheck.datacheck.files",
    "text_peek": "metacheck.datacheck.files",
    "txt_classify_content": "metacheck.datacheck.files",
    # code checks
    "code_abs_path": "metacheck.codecheck.core",
    "code_extract_py": "metacheck.codecheck.core",
    "code_extract_qmd_py": "metacheck.codecheck.core",
    "code_extract_r": "metacheck.codecheck.core",
    "code_file_refs": "metacheck.codecheck.core",
    "code_install_packages": "metacheck.codecheck.core",
    "code_lang": "metacheck.codecheck.core",
    "code_library_lines": "metacheck.codecheck.core",
    "code_library_names": "metacheck.codecheck.core",
    "code_line_stats": "metacheck.codecheck.core",
    "code_packages": "metacheck.codecheck.core",
    "code_parse_r": "metacheck.codecheck.core",
    "code_read": "metacheck.codecheck.core",
    "code_remove_comments": "metacheck.codecheck.core",
    "code_setwd": "metacheck.codecheck.core",
    # statistical software output
    "export_jasp_html": "metacheck.statout.jasp",
    "import_jasp": "metacheck.statout.jasp",
    "match_reported_output": "metacheck.statout.match_reported",
    "export_mplus_html": "metacheck.statout.mplus",
    "import_mplus_output": "metacheck.statout.mplus",
    "export_omv_html": "metacheck.statout.omv",
    "import_omv": "metacheck.statout.omv",
    "read_r_output": "metacheck.statout.r_output",
    "export_spv_html": "metacheck.statout.spv",
    "import_spv": "metacheck.statout.spv",
    "stat_output_json": "metacheck.statout.stat_output",
    "stat_output_validate": "metacheck.statout.stat_output",
    "stat_output_write": "metacheck.statout.stat_output",
    "stat_results_long": "metacheck.statout.stat_output",
    "read_stat_tables": "metacheck.statout.stat_tables",
    "export_stata_smcl_html": "metacheck.statout.stata",
    "import_stata_smcl": "metacheck.statout.stata",
    "stato_type_column": "metacheck.statout.stato_map",
    # computational reproducibility
    "repro_defined_vars": "metacheck.repro.core",
    "repro_dependencies": "metacheck.repro.core",
    "repro_file_io": "metacheck.repro.core",
    "repro_install_deps": "metacheck.repro.core",
    "repro_materialize_layout": "metacheck.repro.core",
    "repro_missing_inputs": "metacheck.repro.core",
    "repro_rewrite_paths": "metacheck.repro.core",
    "repro_run_order": "metacheck.repro.core",
    "repro_run_scripts": "metacheck.repro.core",
    "repro_write_scripts": "metacheck.repro.core",
    "repro_docker_available": "metacheck.repro.docker",
    "repro_install_deps_docker": "metacheck.repro.docker",
    "repro_run_scripts_docker": "metacheck.repro.docker",
    # report building blocks
    "cap_gate_count": "metacheck.report.blocks",
    "collapse_section": "metacheck.report.blocks",
    "format_ref": "metacheck.report.blocks",
    "link": "metacheck.report.blocks",
    "scroll_table": "metacheck.report.blocks",
    # utilities
    "plural": "metacheck._r.base",
    "coerce_paper": "metacheck.papers.io",
    "is_paper": "metacheck.papers.model",
    "is_paper_list": "metacheck.papers.model",
    "load_schema": "metacheck.papers.schema",
    "message": "metacheck.utils",
    "online": "metacheck.utils",
    "path_sanitize": "metacheck.utils",
    "pb": "metacheck.utils",
    "rep_if": "metacheck.utils",
    # --- end of generated metacheck API ---
}

__all__ = ["UPSTREAM", "__version__", *sorted(_EXPORTS)]


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module 'metacheck' has no attribute {name!r}")
    value = getattr(importlib.import_module(target), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))


if TYPE_CHECKING:  # pragma: no cover
    from metacheck.config import cache_dir, email, verbose
    from metacheck.datacheck.scales import scales
    from metacheck.datacheck.tasks import tasks
    from metacheck.fileinfo.types import file_types
    from metacheck.io.bibr import chew
    from metacheck.io.read import read
    from metacheck.log import lastlog, logger, logpath
    from metacheck.module import (
        ModuleError,
        ModuleOutput,
        ModuleSpec,
        get_prev_outputs,
        module,
        module_help,
        module_info,
        module_list,
        module_run,
        run_session,
        use,
    )
    from metacheck.packs.check import CheckIssue, pack_check
    from metacheck.packs.install import (
        pack_install,
        pack_list,
        pack_remove,
        pack_show,
        pack_update,
    )
    from metacheck.packs.registry import refresh
    from metacheck.packs.scaffold import module_template, pack_new
    from metacheck.packs.stores import (
        store_add,
        store_list,
        store_remove,
        store_search,
        store_update,
    )
    from metacheck.papers import (
        Paper,
        PaperList,
        PaperValidationError,
        demofile,
        demopaper,
        from_bibr,
        paper,
        paper_id,
        paper_table,
        paper_validate,
        paper_write,
        read_bibr,
        ref_table,
        test_paper,
    )
    from metacheck.presets import preset, preset_list
    from metacheck.provenance import ModuleChain, RunRecord, rerun, run_modules
    from metacheck.report.blocks import report_table
    from metacheck.report.emojis import emojis
    from metacheck.report.report import (
        module_report,
        report,
        report_module_run,
        report_qmd,
        report_repository,
    )
    from metacheck.stats.core import stats
    from metacheck.stats.statcheck import statcheck
    from metacheck.text import (
        causal_relations,
        expand_text,
        extract_eq,
        extract_p_values,
        extract_urls,
        search_text,
        text_expand,
        text_search,
    )
    from metacheck.text.extract_tests import extract_tests
    from metacheck.text.json_expand import json_expand
    from metacheck.validate import accuracy, validate


# --- metacheck API imports (generated by scripts/sync_exports.py; do not edit below) ---
if TYPE_CHECKING:  # pragma: no cover
    from metacheck._r.base import plural
    from metacheck.archives.aspredicted import aspredicted_info, aspredicted_links
    from metacheck.archives.cache import metacheck_cache_info
    from metacheck.archives.dataone import dataone_info, dataone_links
    from metacheck.archives.dataverse import (
        dataverse_file_download,
        dataverse_info,
        dataverse_links,
        dataverse_pat,
    )
    from metacheck.archives.download import (
        download_repo_files,
        repo_cache_clear,
        repo_cache_dir,
        repo_cache_size,
    )
    from metacheck.archives.dryad import (
        dryad_auth,
        dryad_file_download,
        dryad_info,
        dryad_links,
        dryad_pat,
    )
    from metacheck.archives.dspace7 import dspace7_file_download, dspace7_links
    from metacheck.archives.figshare import (
        figshare_file_download,
        figshare_info,
        figshare_links,
        figshare_pat,
    )
    from metacheck.archives.fourtu import (
        researchdata4tu_file_download,
        researchdata4tu_info,
        researchdata4tu_links,
        researchdata4tu_pat,
    )
    from metacheck.archives.fsd import fsd_info, fsd_links
    from metacheck.archives.github import (
        github_files,
        github_info,
        github_languages,
        github_links,
        github_readme,
        github_repo,
        github_tree_files,
    )
    from metacheck.archives.gitlab import gitlab_links, gitlab_pat, gitlab_repo, gitlab_tree_files
    from metacheck.archives.info_cache import repo_info_cache, repo_info_cache_clear
    from metacheck.archives.local import local_files
    from metacheck.archives.mendeley import mendeley_info, mendeley_links
    from metacheck.archives.osf import (
        osf_api_check,
        osf_cache_clear,
        osf_check_id,
        osf_delay,
        osf_file_download,
        osf_get_all_pages,
        osf_info,
        osf_links,
        osf_preprint_list,
        osf_type,
    )
    from metacheck.archives.osf_helpers import osf_pat, osf_user_projects
    from metacheck.archives.psycharchives import (
        dspace_links,
        psycharchives_file_download,
        psycharchives_info,
        psycharchives_links,
    )
    from metacheck.archives.researchbox import rbox_file_download, rbox_info, rbox_links
    from metacheck.archives.reshare import reshare_file_download, reshare_info, reshare_links
    from metacheck.archives.zenodo import zenodo_file_download, zenodo_info, zenodo_links
    from metacheck.archives.zenodo_upload import zenodo_pat, zenodo_upload
    from metacheck.archives.zip_peek import zip_decision, zip_peek
    from metacheck.archives.zip_peek_cache import zip_peek_cache_clear
    from metacheck.codecheck.core import (
        code_abs_path,
        code_extract_py,
        code_extract_qmd_py,
        code_extract_r,
        code_file_refs,
        code_install_packages,
        code_lang,
        code_library_lines,
        code_library_names,
        code_line_stats,
        code_packages,
        code_parse_r,
        code_read,
        code_remove_comments,
        code_setwd,
    )
    from metacheck.datacheck.checks import (
        data_check_case_issues,
        data_check_colname,
        data_check_colname_collisions,
        data_check_constant,
        data_check_demographic,
        data_check_design_name,
        data_check_empty,
        data_check_is_behaverse,
        data_check_is_inquisit,
        data_check_is_jspsych,
        data_check_is_psychopy,
        data_check_is_qualtrics,
        data_check_numeric_in_text,
        data_check_outliers,
        data_check_pii_freetext,
        data_check_pii_geo,
        data_check_pii_name,
        data_check_pii_values,
        data_check_scale_values,
        data_check_spss_filter,
        data_check_whitespace,
        data_col_concept,
        data_col_facets,
        data_promote_header_row,
        data_strip_qualtrics_header,
    )
    from metacheck.datacheck.columns import (
        data_col_stats,
        data_col_type,
        match_column_labels,
        parse_codebook,
        parse_qsf,
    )
    from metacheck.datacheck.files import (
        data_classify_files,
        data_format,
        data_group_llm,
        data_is_manifest,
        data_read_head,
        data_study_roster,
        manifest_merge,
        text_peek,
        txt_classify_content,
    )
    from metacheck.db.crossref import (
        add_bib_match,
        crossref_doi,
        crossref_query,
        datacite_doi,
        openalex_doi,
        openalex_query,
    )
    from metacheck.db.doi import doi_clean, doi_lookup, doi_resolves, doi_valid_format
    from metacheck.db.orcid import check_orcid, credit_roles, get_orcid, orcid_person
    from metacheck.db.pubpeer import pubpeer_comments
    from metacheck.db.regcheck import regcheck_base_url, regcheck_compare, regcheck_tidy
    from metacheck.db.regcheck_local import (
        regcheck_setup_local,
        regcheck_start_local,
        regcheck_stop_local,
    )
    from metacheck.db.replications import FLoRA, FLoRA_date, FLoRA_update
    from metacheck.db.retractionwatch import retractionwatch, rw, rw_date, rw_update
    from metacheck.fileinfo.category import file_category, filetype
    from metacheck.fileinfo.naming import check_file_naming
    from metacheck.io.bibr_convert import convert_bibr, format_bib_authors
    from metacheck.io.convert import convert
    from metacheck.io.corpus import papers_available, papers_load, papers_metadata, papers_remove
    from metacheck.io.grobid import convert_grobid, grobid_to_bibr
    from metacheck.llm.cache import llm_cache, llm_cache_clear
    from metacheck.llm.core import (
        llm,
        llm_max_calls,
        llm_max_tokens,
        llm_model,
        llm_model_list,
        llm_reasoning,
        llm_timeout,
        llm_use,
    )
    from metacheck.papers.io import coerce_paper
    from metacheck.papers.model import is_paper, is_paper_list
    from metacheck.papers.schema import load_schema
    from metacheck.report.blocks import (
        cap_gate_count,
        collapse_section,
        format_ref,
        link,
        scroll_table,
    )
    from metacheck.repro.core import (
        repro_defined_vars,
        repro_dependencies,
        repro_file_io,
        repro_install_deps,
        repro_materialize_layout,
        repro_missing_inputs,
        repro_rewrite_paths,
        repro_run_order,
        repro_run_scripts,
        repro_write_scripts,
    )
    from metacheck.repro.docker import (
        repro_docker_available,
        repro_install_deps_docker,
        repro_run_scripts_docker,
    )
    from metacheck.statout.jasp import export_jasp_html, import_jasp
    from metacheck.statout.match_reported import match_reported_output
    from metacheck.statout.mplus import export_mplus_html, import_mplus_output
    from metacheck.statout.omv import export_omv_html, import_omv
    from metacheck.statout.r_output import read_r_output
    from metacheck.statout.spv import export_spv_html, import_spv
    from metacheck.statout.stat_output import (
        stat_output_json,
        stat_output_validate,
        stat_output_write,
        stat_results_long,
    )
    from metacheck.statout.stat_tables import read_stat_tables
    from metacheck.statout.stata import export_stata_smcl_html, import_stata_smcl
    from metacheck.statout.stato_map import stato_type_column
    from metacheck.utils import message, online, path_sanitize, pb, rep_if
